### ISSUE TITLE
Navidrome doesn't sort tracks properly when using vinyl numbering

### ISSUE THREAD

**Issue by BRTPOB** [navidrome/navidrome#2104] opened 2023-01-21 20:11 UTC
I've got an LP that a friend ripped for me, and in the metadata he numbered them A1-4; B1-4, etc. Inside of Navidrome, however, the metadata shows 0 for the track numbering, and it simply defaulted to sorting alphabetically. Screenshot attached of the behaviour seen.

![image](https://user-images.githubusercontent.com/7201028/213885405-ae947e85-5534-4237-a301-b42a65d28d5c.png)

**Comment by K4r0qtuYNE5G4qgZ** [comment] 2023-01-22 22:31
Yeah it only supports numbers with or without leading zeroes.

That's why i hate Discoqs that sometimes uses 1.1,1.2,.. for tracks instead cleanly separating discnumbers and tracks and they are also the ones using A, B, C,.. for Vinyl or sometimes tracks with or without leading zeroes and even I, II, III, IV etc.

Musicbrainz is much more consistent and clean there, it always uses numbers with leading zeroes.

But luckily it's easy to quickly renumber the tracks with MP3Tag's auto-numbering wizard, I now do that automatically for Discoqs to clean up their mess. Because what I need is discnumbers and tracknumbers with leading zeroes so that when renaming, the files are sorted cleanly and correctly also in the filesystem when there are 10+ tracks and or discs. 

Also the A, B, C,.. for Vinyl is wrong anyway, because that's the sides not the tracknumbers, so theoretically that are more discnumbers than tracknumbers, really dunno why discoqs not also simply uniformly use numbers with leading zeroes like Musicbrainz does, would save me and probably others too, a lot of work.

**Comment by certuna** [comment] 2023-01-24 14:47
Duplicate of this issue: https://github.com/navidrome/navidrome/issues/1652

**Closed** 2023-01-24 15:59 UTC
Labels: duplicate
