### ISSUE TITLE
when I import music，there is no artist and album info

### ISSUE THREAD

**Issue by juanmaocxy** [navidrome/navidrome#2054] opened 2022-12-21 04:47 UTC
docker-compose：
version: '2.4'
services:
  navidrome:
    image: deluan/navidrome:pr-2032
    container_name: navidrome
    environment:
      - PUID=1000
      - PGID=1000
      - ND_LASTFM_ENABLED=true
      - ND_LASTFM_LANGUAGE=zh
      - ND_SCANSCHEDULE=5m
      - ND_ENABLETRANSCODINGCONFIG=true
      - ND_LOGLEVEL=info
      - ND_LASTFM_APIKEY=60dd271393e6351826c2dcf42feb2bb7
      - ND_LASTFM_SECRET=ffbd864757b7848424908f7dc26f6995
      - ND_SPOTIFY_ID=3b5145df0ed447269e3acc3f43747d8e
      - ND_SPOTIFY_SECRET=08ed5b7645ea4ab489062eb3d11d8806
    mem_limit: 500m
    volumes:
      - /mnt/md0/appdata/container/navidrome/data:/data
      - /mnt/md0/appdata/container/navidrome/music:/music:ro
    ports:
      - 350:4533
    restart: always

when I import music,the music is belong to unknow album and no artist info.

I want to know how can I solve it
![image](https://user-images.githubusercontent.com/58592452/208823848-94496ea0-b039-4fe3-83fc-251a92abdb96.png)

**Comment by deluan** [comment] 2022-12-21 14:52
Can you confirm your files have proper "artist" and "album" tags? If yes, can you attach one of the files here?

**Comment by juanmaocxy** [comment] 2022-12-22 06:49
> Can you confirm your files have proper "artist" and "album" tags? If yes, can you attach one of the files here?
> 
> 你能确认你的文件有正确的“艺术家”和“专辑”标签吗？如果是，您能否在此处附上其中一个文件？
here is my music file
[http://gstore-static.oss-cn-hangzhou.aliyuncs.com/abcaaa/music.zip](url)
Thank you!!

**Comment by deluan** [comment] 2022-12-22 14:33
As I suspected your files are not tagged. You need to tag them with some tool like MusicBrainz Picard, beets, kid3, mp3tag, etc... See more options here: https://www.navidrome.org/docs/faq/#how-can-i-edit-my-music-metadata-id3-tags-how-can-i-renamemove-my-files

Navidrome reads info from the tags, not the file names. Closing this, as it is not a bug.

**Closed by deluan** 2022-12-22 14:33 UTC
Labels: bug

**Comment by juanmaocxy** [comment] 2022-12-22 14:39
> As I suspected your files are not tagged. You need to tag them with some tool like MusicBrainz Picard, beets, kid3, mp3tag, etc... See more options here: https://www.navidrome.org/docs/faq/#how-can-i-edit-my-music-metadata-id3-tags-how-can-i-renamemove-my-files
> 
> Navidrome reads info from the tags, not the file names. Closing this, as it is not a bug.

ok,thank you,I'll give it a try
