### ISSUE TITLE
Cover art broken

### ISSUE THREAD

**Issue by bartkummel** [navidrome/navidrome#2132] opened 2023-01-31 11:33 UTC
### Description

After updating to 0.49, none of my clients (including the Navidrome UI) show any album art anymore. I get warnings in the log like these:
```
time="2023-01-31T11:22:35Z" level=warning msg="HTTP: GET http://<host>/rest/getCoverArt.view?t=[REDACTED]&c=submariner&id=al-9fffd1a8c95b932c1ba749da4ccfd7d3&u=bart&size=300&v=1.5.0&s=[REDACTED]" elapsedTime=1m httpStatus=429 remoteAddr=192.168.1.1 requestId=87906a92a61b/U3TnNdkEt0-001649 responseSize=22
...
time="2023-01-31T11:21:22Z" level=warning msg="HTTP: GET http://<host>/rest/getCoverArt?u=[REDACTED]&t=[REDACTED]&s=[REDACTED]&f=json&v=1.8.0&c=NavidromeUI&id=al-9158c3ffce53045ff6f2f1dbc0160e86&_=2022-03-13T15%3A47%3A19.473242225Z&size=300" elapsedTime=1m httpStatus=429 remoteAddr=192.168.1.1 requestId=87906a92a61b/U3TnNdkEt0-001572 responseSize=59
```
Also, some clients give "request timed out" errors.

### Expected Behaviour

Cover art should load when available.

### Steps to reproduce

- Upgrade to 0.49
- Log in to one or more clients and/or the Navidrome UI.
- See that there's no cover art 

### Platform information

 - Navidrome version: v0.49 (25374b3b)
 - Browser and version: Arc Version 0.87.0 (36910); Chromium Engine Version 109.0.5414.119
 - Operating System: Docker image running on Synology NAS, DSM 7.1.1-42962 Update 3

### Additional information
<img width="539" alt="Scherm­afbeelding 2023-01-31 om 12 31 34" src="https://user-images.githubusercontent.com/20771942/215748781-452012e1-063b-4b6e-8569-03aa2cbb9ff6.png">
<img width="498" alt="Scherm­afbeelding 2023-01-31 om 12 30 51" src="https://user-images.githubusercontent.com/20771942/215748785-a6d38d6e-9c49-492a-8226-9e5b22207789.png">

Clients I tried:
- Navidrome UI
- Submariner 2.0 (on macOS)
- Amperfy 1.1.1 (build 2) on iOS

**Comment by bartkummel** [comment] 2023-01-31 11:49
Let me nuance this a little bit: serving the images is just really, really slow. After leaving open the UI for a while, some images start to be shown. But paginating to a page that I hadn't visited before, I get time outs again.

**Comment by deluan** [comment] 2023-01-31 15:35
I've seen that behaviour once, but was not able to reproduce it again. I know this is not a solution but have you tried to restart Navidrome after these timeouts occurred? Try stopping Navidrome, removing the image cache (`$DataFolder/cache/images`) and starting it again. Let me know if this resolves the issue.

**Comment by nagarrido** [comment] 2023-01-31 16:13
I had the same problem and deleting thebcache worked for me!

**Comment by bartkummel** [comment] 2023-01-31 16:40
@deluan Restarting didn't help. Waiting a long time seemed to solve it for me. I'll try to empty the cache if it happens again.

**Comment by deluan** [comment] 2023-02-01 15:53
Will close this for now. Feel free to reopen if the issue happens again.

**Closed by deluan** 2023-02-01 15:53 UTC
Labels: bug

**Comment by jan666** [comment] 2023-02-02 13:19
Same issue, same fix (deleting cache)
