### ISSUE TITLE
Allow for configuration of album grouping tags

### ISSUE THREAD

**Issue by Auran64** [navidrome/navidrome#2220] opened 2023-03-02 02:19 UTC
### Is your feature request related to a problem? Please describe.

I have a large music library and some of the artists in it have multiple albums with the exact same title, released in different years. Personally, I like to keep these with the proper name as is (instead of, say, "Self-Titled (1968)", "Self-Titled (1971)" and so on). However, with Navidrome these albums are grouped together and there's not much I can do about it without changing those tags. My daily driver music player has a setting to allow for albums to be grouped by album artist, album name, _and_ year, unlike the way Navidrome works with no way to change it.

### Describe the solution you'd like

Add a configuration setting that allows users to establish how albums are grouped together based on whichever tags the user wants.

### Describe alternative solutions that would also satisfy this problem

Possibly making albums group by year by default? Although that would mess with compilation albums depending on how those are tagged.

### Additional context

![image](https://user-images.githubusercontent.com/126738276/222313992-ba2ffb47-9718-4a1f-afae-dcb872851970.png)
This is how it behaves in my go-to music player.

![image](https://user-images.githubusercontent.com/126738276/222313814-eb16c17c-bc41-433e-b70e-77029066d3c5.png)
This is how it behaves in Navidrome.

**Comment by certuna** [comment] 2023-03-06 14:49
This PR: https://github.com/navidrome/navidrome/pull/2162 allows for splitting albums by Release Date, so as long as the two same-named albums are tagged with different release dates, they will appear as two separate albums.

**Comment by deluan** [comment] 2023-03-07 01:36
Hey @Auran64 , as I mentioned in Discord, this is planned but not implemented yet: https://github.com/navidrome/navidrome/issues/1976#issuecomment-1383278483

In the meantime, @certuna#7396 's  PR will probably help you. I'm planning to have it merged for next release.

Closing this as a duplicate of #1976. Please subscribe to that issue for updates.

**Closed by deluan** 2023-03-07 01:36 UTC
Labels: enhancement
