### ISSUE TITLE
Whether sharing function can be supported

### ISSUE THREAD

**Issue by Proselyte-M** [navidrome/navidrome#2042] opened 2022-12-15 04:22 UTC
When I need to share music with friends, I hope to have a function that allows me to listen to music without an account password.

I noticed that [airsonic-advanced](https://github.com/airsonic-advanced/airsonic-advanced) has this function. It's just because the performance of [airsonic-advanced](https://github.com/airsonic-advanced/airsonic-advanced) is too large for me to use.

Can you add this feature

thank you

I'm sorry that my mother tongue is not English. Please forgive me for any offence in the text.

Use AI to translate into English.

**Comment by metalheim** [comment] 2022-12-15 06:56
I think this is a duplicate of #748

**Comment by deluan** [comment] 2023-01-22 20:12
Yes, it is a duplicate of #748. I'm working on it in #2106

**Closed by deluan** 2023-01-22 20:12 UTC
Labels: enhancement
