### ISSUE TITLE
[Bug]: 'Invalid API key.' when enabling last.fm scrobbling on 0.51.1 (works with 0.51.0)

### ISSUE THREAD

**Issue by wundor** [navidrome/navidrome#2896] opened 2024-03-09 16:57 UTC
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.1

### Current Behavior

This error on last.fm `Connect application` page

```
Invalid API key. If you are a third party developer see our authentication how-to to find out more.
```

**I'm thinking that's because of the `api_key=null` in the request URL**

```
https://www.last.fm/api/auth?api_key=null&cb=https://example.com/api/lastfm/link/callback?uid=xxx
```

### Expected Behavior

I should get the 'Connect application' page without errors that prompts me to connect new app

### Steps To Reproduce

0. Upgrade to 0.51.1. **No such error on 0.51.0**
1. Generate Last.fm app key (as required by [v0.51.0](https://github.com/navidrome/navidrome/releases/tag/v0.51.0)) and paste them into config
2. Go to `https://example.com/app/#/personal` and click on 'Scrobble to Last.fm'
3. Observe the error from Last.fm in the new tab

### Environment

```markdown
- OS: Arch Linux
- Browser: Firefox 123
- Client: Default Navidrome web UI
```

### How Navidrome is installed?

Docker

### Configuration

```toml
---
version: '3.9'
services:
  navidrome:
    image: deluan/navidrome:0.51.1
    volumes:
      - /srv/navidrome/data/app:/data
      - /srv/navidrome/data/music:/music:ro
    networks:
      - traefik-edge
      - default
    environment:
      ND_SCANSCHEDULE: "1h"
      ND_LOGLEVEL: "info"
      ND_SESSIONTIMEOUT: "720h"
      ND_UIWELCOMEMESSAGE: xxx"
      ND_PROMETHEUS_ENABLED: "true"
      ND_IMAGECACHESIZE: 0
      ND_COVERARTPRIORITY: "cover.*, folder.*, embedded"
      ND_ENABLETRANSCODINGCONFIG: "true"
      ND_LASTFM_APIKEY: "xxx"
      ND_LASTFM_SECRET: "xxx"
      ND_SPOTIFY_ID: "xxx"
      ND_SPOTIFY_SECRET: "xxx"
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik-edge'
        - 'traefik.http.routers.navidrome.rule=Host(`xxx`)'
        - 'traefik.http.routers.navidrome.tls=true'
        - 'traefik.http.routers.navidrome.entrypoints=https'
        - 'traefik.http.routers.navidrome.middlewares=lan-whitelist'
        - 'traefik.http.services.navidrome.loadbalancer.server.port=4533'

networks:
  traefik-edge:
    external: true
```

### Relevant log output

```shell
I found nothing
```

### Anything else?

Just to reiterate: it works with `0.51.0`

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by Porygon31** [comment] 2024-03-10 16:33
Same for me 
I'm using PikaPods

**Comment by hazre** [comment] 2024-03-11 17:40
I am also having this issue. rolling back to 0.51.0 fixed it.

**Comment by dweymouth** [comment] 2024-03-12 19:18
See here: https://www.reddit.com/r/navidrome/comments/183wypy/important_update_navidrome_to_remove_shared/

Navidrome got asked by Last.FM to remove its builtin API key. Going forward, you will have to set up the Last.FM integration with your own API key. Instructions here: https://www.navidrome.org/docs/usage/external-integrations/

**Comment by hazre** [comment] 2024-03-12 23:38
This https://github.com/navidrome/navidrome/pull/2905 PR fixes the problem. Looks like in 0.51.1 the lastfm api config was deleted by accident.

**Comment by tw0flower** [comment] 2024-03-13 20:20
I reproduced what @wundor describes as well. However, simply deleting the local cache fixed the issue for me.

In Firefox, open the developper tools (Ctrl+Shift+I), go to the Storage tab, select your Navidrome URL in Local Storage in the left panel and delete everything. You will have to login again.

My experience is maybe slightly different because I did not use the last.fm integration before, but from my point of view clearing the local storage is all that's needed to fix this issue.

**Comment by joedawson** [comment] 2024-03-13 21:15
This also worked for me @tw0flower, thank you.

**Comment by deluan** [comment] 2024-04-03 00:19
Sorry for the late reply, but just logging out and logging in again should be enough for "fixing" the issue. 

@hazre, removing the line https://github.com/navidrome/navidrome/blob/859cdda0bdaa67cc92e8312c2be13f12cb89fddb/ui/src/authProvider.js#L24 was not accidental, it was the whole reason for that commit (see https://github.com/navidrome/navidrome/issues/2829#issuecomment-1915968017)

Unfortunately it caused this undesired side-effect. I'll think about some better solution, but I think by the time I get it done, this will be a non-issue, as probably everyone running 0.51.1 will have logged out and in at least once :)

**Comment by protist** [comment] 2024-04-11 00:40
@deluan I ran into the problem a little while ago with the "Invalid API key", and rolled back to 0.50.2 (I think this is a version one before the version others suggest here). On your suggestion, I just tried to upgrade to 0.51.1, but for some reason this time there is no `Scrobble to Last.fm` switch

![navidrome](https://github.com/navidrome/navidrome/assets/646668/9e4e03ac-32cf-4e21-af12-4d2c2a6102a5)

I rolled back to 0.50.2, and the switch is there again.

![Screenshot_240411_104013](https://github.com/navidrome/navidrome/assets/646668/cd923c79-7749-4f5a-992d-2d9a86d6b6ed)

**Comment by hobhobuk** [comment] 2024-04-17 15:03
Same issue here.. new install, just installed today.
No toggle exists for last.fm.

Followed the guide, added the text needed to the config file, still no toggle.. no prompts.. not working.

**Comment by deluan** [comment] 2024-04-17 17:30
@protist and @hobhobuk : After upgrading to 0.51.1, try logging out, refresh the page (Ctrl-R) and login again.

Also keep in mind that in version 0.51.0, [we removed the shared Last.fm API-Key/Secret](https://github.com/navidrome/navidrome/releases/tag/v0.51.0). You need to [create your own API-Key](https://www.navidrome.org/docs/usage/external-integrations/#lastfm) for the option to be available.

I'll close this issue as it is resolved by logout/refresh/login (and making sure you have the Last.fm API-Key/Secret configured).

**Closed by deluan** 2024-04-17 17:30 UTC
Labels: bug, triage

**Comment by nulledone** [comment] 2024-04-17 22:33
I have tried to do the workaround mentioned above but I get: 
```
An error occurred while authorizing with Last.fm. 
Request ID: 1a9906e97244/WzvpnGe1qz-000118
```

**Comment by deluan** [comment] 2024-04-18 02:23
@nulledone Please open a a new issue and please add more details from the logs and from what exactly you tried, version, etc....

**Comment by protist** [comment] 2024-04-20 01:37
> Also keep in mind that in version 0.51.0, [we removed the shared Last.fm API-Key/Secret](https://github.com/navidrome/navidrome/releases/tag/v0.51.0). You need to [create your own API-Key](https://www.navidrome.org/docs/usage/external-integrations/#lastfm) for the option to be available.

Oops, I missed that. Thanks @deluan that fixed it. For the record, I also had to toggle the `Scrobble to Last.fm` switch in the web GUI off then on.

**Comment by muhdusama** [comment] 2024-05-08 11:46
Opening in Incognito window and trying again seems to have fixed it for me. Looks like a cache issue.

**Comment by jonaskohl** [comment] 2024-06-18 09:23
> Opening in Incognito window and trying again seems to have fixed it for me. Looks like a cache issue.

I solved it by opening the Firefox DevTools, go to the storage tab and delete everything related to your Navidrome URL, including cache, cookies and LocalStorage. After that, I had to log back in and now the API key was correctly included in the Last.fm URL.

**Comment by adm72** [comment] 2024-09-15 06:15
I opened Navidrome through another browser, and that also solved the problem.

**Comment by jm355** [comment] 2025-01-12 15:09
On navidrome 0.54.3, with `ND_LASTFM_APIKEY` and `ND_LASTFM_SECRET` set, and trying both in incognito mode and after signing out and deleting all cache, cookies, storage in developer settings, I still get "Invalid API key. If you are a third party developer see our authentication how-to to find out more." in last.fm
