### ISSUE TITLE
[Bug]: Only 200 songs can be added to Play Queue 

### ISSUE THREAD

**Issue by DECsystem20** [navidrome/navidrome#2712] opened 2023-12-17 18:08 UTC
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.50.2

### Current Behavior

Only 200 songs are added to Play Queue from Artists tab.

### Expected Behavior

User is able to add all songs from one artist to Play Queue.

### Steps To Reproduce

1. Open Artists tab
2. Click three dots on an artist with more than 200 songs
3. Click Play 
4. Only 200 songs is added to Play Queue

### Environment

```markdown
- OS: Fedora 39
- Browser: Chrome 120.0.6099.109
```

### How Navidrome is installed?

Docker

### Configuration

```toml
Navidrome is deployed with ansible, using these environment variables:

env:
  ND_MUSICFOLDER: "/music"
  ND_DATAFOLDER: "/data"
  ND_SCANSCHEDULE: "12h"
  ND_LOGLEVEL: "info"
  ND_SESSIONTIMEOUT: "24h"
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment] 2023-12-17 19:05
Thanks for reaching out. 

This is not a bug, it is working as intended. Because the way the current player works, if we leave this value unbound it could potentially kill/freeze the UI as it could have too many songs in the playqueue, and it has to keep it all in memory. 

This will be taken in consideration when we replace the current player with another implementation. 

Will close this for now, as it is not a bug.

**Closed by deluan** 2023-12-17 19:05 UTC
Labels: bug, triage

**Comment by DECsystem20** [comment] 2023-12-18 18:38
Thank you for clarifying :)
