### ISSUE TITLE
navidrome build fails when nodejs 16 is built against OpenSSL 3.0

### ISSUE THREAD

**Issue by pimzand** [navidrome/navidrome#1768] opened 2022-06-12 16:15 UTC
### Description

Fedora 36 comes with nodejs v16.14.0 built against OpenSSL 3.0.
In this environment, navidrome will not build.

### Expected Behaviour

navidrome builds, just like in Fedora 35, where the same version of nodejs is built against OpenSSL 1.1.

### Steps to reproduce

1. git clone https://github.com/navidrome/navidrome.git 
2. cd navidrome
3. make setup
4. make buildall
5. see error

```
> navidrome-ui@0.1.0 build
> react-scripts build

Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/pim/os/linux/sound/forks/navidrome/ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/pim/os/linux/sound/forks/navidrome/ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/pim/os/linux/sound/forks/navidrome/ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/pim/os/linux/sound/forks/navidrome/ui/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/pim/os/linux/sound/forks/navidrome/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/pim/os/linux/sound/forks/navidrome/ui/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/pim/os/linux/sound/forks/navidrome/ui/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/pim/os/linux/sound/forks/navidrome/ui/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/pim/os/linux/sound/forks/navidrome/ui/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/pim/os/linux/sound/forks/navidrome/ui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/pim/os/linux/sound/forks/navidrome/ui/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
make: *** [Makefile:78: buildjs] Error 1
```

### Platform information

 - Navidrome version: latest git
 - Browser and version: n/a
 - Operating System: Fedora 36
 - Nodejs 16.14.0

### Additional information
node 17 adds a new option '--openssl-legacy-provider' to make it run, which is mentioned in various github bug reports. This is not available with node 16 and so there is no possibility to build navidrome.

Upstream bug to backport '--openssl-legacy-provider' to node 16 is here:
  https://github.com/nodejs/node/issues/40948

Original issue with node 17 is here: 
  https://github.com/nodejs/node/issues/40455

Fedora packagers refuse to add the  '--openssl-legacy-provider'  option:
  https://bugzilla.redhat.com/show_bug.cgi?id=2073502

Their comment is:

> The '--openssl-legacy-provider' option is not a fix, it's a workaround that significantly reduces security for Node.js.
> 
> The correct solution is for JS packages to stop using MD4, which has been unsafe since *1995*. Projects have had more than a quarter-century to avoid this problem. Realistically, if they haven't fixed it by now, Node.js failing to work with it is probably the only way to push them to it.
> 
> If Node.js upstream decides to include the `--openssl-legacy-provider` option in a future release of 16.x, we will get it as part of the normal course of updates. I will still strongly advise against using it.

**Comment by pimzand** [comment] 2022-06-12 19:10
The problem is caused by webpack 4.44.2.
It uses MD4 hashes, no longer supported by OpenSSL.

Rather than seeking options to downgrade security, the solution should be to fix webpack.
One way would be to upgrade to webpack 5, but even the current version can be patched.

The patch described here worked for me:
https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

I now need to figure out how to automate this patch, so it can be part of the navidrome distribution or a Fedora srpm.

**Comment by deluan** [comment] 2022-09-29 01:35
@pimzand Thanks for updating the PR. I decided to take a fresh look at the problem, and after being able to reproduce the issue in a fedora:36 container, I upgraded react-scripts to v5 (which also upgrades webpack to v5) and seems that the issue is gone. 

I pushed the changes to master, can you please confirm it works now? Thanks!

**Comment by pimzand** [comment] 2022-09-29 13:49
@deluan Thank you for this fix. This is much better than the hack I used in the PR. This will benefit not just
Fedora users. Recently there was a comment from @mweinelt that indicates the same issue is present in NixOS:
https://github.com/navidrome/navidrome/pull/1767#issuecomment-1257169200

**Comment by deluan** [comment] 2022-09-29 14:39
Great! Closing this now, as the issue is resolved. Thanks for the collaboration!

**Closed by deluan** 2022-09-29 14:39 UTC
Labels: bug
