### ISSUE TITLE
Personal configuration in WebUi don't save

### ISSUE THREAD

**Issue by DowXor** [navidrome/navidrome#1070] opened 2021-04-29 08:37 UTC
Hello,

### Description

After modifying an item in the personal configuration, when I quit navidrome and come back, the configuration is always the default.

### Expected Behaviour

I would like my configuration to be saved for any users.

### Steps to reproduce

I use a private navigation for test this (I'm sure the cache doesn't save it)

1. Connect to Navidrome
2. Click on 'Personal'
3. Modify language or theme
4. Return on home page
5. Close private navigation
6. Open and connect to Navidrome
7. Configuration not saved

### Platform information

 - Navidrome version: v0.42.0
 - Browser and version: Brave Version 1.23.73 in Chromium: 90.0.4430.85 (Build officiel) (64 bits)
 - Operating System: Debian 10 - Binary

Thanks

**Comment by deluan** [comment] 2021-04-29 13:46
Personal configuration is saved in the browser's `localStorage`. When using private navigation, the `localStorage` is deleted when you close it, hence you won't be able to save preferences in that window.

Can you reproduce the issue with a regular (not private) window in your browser?

**Comment by DowXor** [comment] 2021-04-29 14:11
Ah OK ! I thought it was save to the database. It's a shame, it could be useful when Navidrome is used between several different equipments.

Thanks for your answer.

**Comment by deluan** [comment] 2021-04-29 14:25
In the future it may save some of the preferences in the server, but the reasoning for not doing this is that, you may want to have different options for different browsers. Ex: use different themes in the desktop and in mobile.

But some prefs are for the user (ex: language), so this may change in the future.

**Closed by deluan** 2021-04-29 14:25 UTC
Labels: bug
