### ISSUE TITLE
Improved artist>album view

### ISSUE THREAD

**Issue by azukaar** [navidrome/navidrome#1468] opened 2021-11-16 14:27 UTC
Currently the view are very simple
 artists
 albums
 songs

and when clicking on an artist, it shows the albums and so on.
In most media library (WMP, Spotify and so on) when clicking on an artist, instead of only showing albums, it shows the songs, grouped by albums (see screenshot).

I think that would be a good improvement to the UI.

Thanks you for the hard work!

![image](https://user-images.githubusercontent.com/7872597/142003460-01e08a3b-0c90-4e41-aefb-147896bb157b.png)

**Comment by certuna** [comment] 2021-11-16 16:19
The current artists/albums/songs views are based on the standard react-admin view templates (see its demo site here: https://marmelab.com/react-admin-demo ), with only small changes.

Other view designs (like this combined albums + tracklists like you propose) are definitely possible to build, but will be a lot more work.

**Comment by azukaar** [comment] 2021-11-16 17:56
I can do a PR for it, if the feature needs to be implemented, i made a local demo to test implementing it already

![image](https://user-images.githubusercontent.com/7872597/142039568-4fe9f4d4-c5a4-4f3d-93e6-f9026eeed0e9.png)

**Comment by certuna** [comment] 2021-11-17 12:28
Cool, shall we connect on Discord?

**Comment by deluan** [comment] 2021-11-17 23:13
I like this idea, reminds me iTunes UI. But I also like the album grid showing only the albums. Maybe a selector to choose which view to use?

**Comment by deluan** [comment] 2021-11-18 02:50
Hey @azukaar I just realized this is actually a duplicate of #961. Can we move the discussion to that issue? Thanks!

**Closed by deluan** 2021-11-18 02:50 UTC
Labels: enhancement
