### ISSUE TITLE
Status of the big play button does not change

### ISSUE THREAD

**Issue by shgurbanov** [navidrome/navidrome#1220] opened 2021-07-01 12:33 UTC
### Description

Status of the play button does not change when mp3 is playing.

### Expected Behaviour

Expected the same status of the play buttons as play-play, stop-stop.

### Steps to reproduce

Play any track, big button doesn't change status to "playing".

### Platform information

 - Navidrome version: v0.44.0
 - Browser and version: Google Chrome Version 91.0.4472.114 (Official Build) (64-bit)
 - Operating System: Windows 10

### Additional information

Screenshot added

![Screenshot 2021-07-01 162758](https://user-images.githubusercontent.com/5786682/124124957-1e158180-da8a-11eb-8fee-455fd08de7ff.jpg)

**Comment by ToadCast** [comment] 2021-07-02 10:25
Hi, I wanna give it a shot with my understanding: I think it's the expected behavior because the Play button (with you red mark) intend to tell to start playing this album from the beginning, whether or not you're already playing it.

But I understand you're point because on Spotify, while you're playing the album, it display a 'pause' button at your red mark position. Honestly, it is not something important IMHO.

**Comment by deluan** [comment] 2021-07-03 03:51
This is the current expected behaviour, but we already have an issue open to tackle this: #973.

I'll close this in favour of that one, please subscribe to that issue for updates.

**Closed by deluan** 2021-07-03 03:51 UTC
Labels: bug
