### ISSUE TITLE
UI Hangs on `handleEvent`

### ISSUE THREAD

**Issue by TheBlueMatt** [navidrome/navidrome#1648] opened 2022-03-10 18:35 UTC
Often when loading a page the Navidrome Web UI completely hangs for 20-30 seconds processing some UI events. Its unclear to me exactly which event is being handled during this time, but it doesn't appear to be correlated with any click or mouse drags.

 - Navidrome version: v0.47.5 built from source
 - Browser and version: Firefox 98
 - Operating System: Debian Linux amd64

Firefox profile available at https://share.firefox.dev/3pTWSIK

**Comment by WhaleJ84** [comment] 2023-03-25 10:18
Could you explain how you know its from `handleEvent`? My UI hangs a lot in a similar fashion but have no idea to pin-point down what it may be from.

**Comment by deluan** [comment] 2023-03-26 23:46
Maybe this issue is related to the Activity Panel, as discussed in #1186?

**Comment by WhaleJ84** [comment] 2023-03-27 10:34
Yes, that seemed to be the case. Setting the development variable in the config as discussed there has prevented the UI hanging for now. Thanks!

**Comment by deluan** [comment] 2023-03-27 13:46
@TheBlueMatt, can you confirm if the workaround in #1186 works for you, please? If that's the case, I'll close this as duplicate.

**Comment by deluan** [comment] 2023-05-19 14:53
Duplicate of #1186.

**Closed** 2023-05-19 14:53 UTC
Labels: bug, duplicate
