### ISSUE TITLE
Auto Playlist Export Option

### ISSUE THREAD

**Issue by Crazy-Ginger** [navidrome/navidrome#2035] opened 2022-12-09 10:12 UTC
Was looking if there was a way to easily sync playlists between my navidrome server and local music players (e.g. foobar). It seems that navidrome can automatically import  playlists but can only manually export them. 

It would be good if there were an option that enabled navidrome to automatically export/update playlists created to the same folder that playlists are imported from. 

Alternatively, the playlists could be exported to another directory separate from the imports, but that seems like an unnecessary duplication of data.

**Comment by TheWrathKing** [comment] 2022-12-09 11:59
Exporting playlists in the same folder as they are imported seems to be a quite impossible option for many because the "MusicFolder" is often (and idealy) mounted read-only

**Comment by Crazy-Ginger** [comment] 2022-12-09 23:55
Would it not be possible to have them exported to a separate directory then?

**Comment by deluan** [comment] 2022-12-21 20:03
Hey @Crazy-Ginger, this is a duplicate of #753, where I explain why this would be [hard to implement](https://github.com/navidrome/navidrome/issues/753#issuecomment-771042972). Anyway, I still have some ideas, and may implement what is described in #753, so please subscribe to that issue to be notified of any updates.

Closing this as a duplicate.

**Closed by deluan** 2022-12-21 20:03 UTC
Labels: enhancement
