### ISSUE TITLE
Navidrome Docker-Container creates large resolv.conf

### ISSUE THREAD

**Issue by quotengrote** [navidrome/navidrome#1179] opened 2021-06-14 11:42 UTC
### Description

After a few Days(>10) the Navidrome docker-Container creates large(>50Gb) resolv.conf.

### Expected Behaviour

...

### Platform information

 - Navidrome version: 0.43.0 (d9f26826)
 - Browser and version: Vivaldi | 4.0.2312.25 (Stable channel) (64-Bit)

### Docker-Compose
```
version: '3'
services:
######## navidrome-mg ########
  navidrome-mg:
    container_name: "navidrome-mg"
    image: deluan/navidrome:latest
    restart: always
    environment:
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_MUSICFOLDER=/music
      - ND_DATAFOLDER=/data
      - ND_TRANSCODINGCACHESIZE=500MB
      - ND_IMAGECACHESIZE=100MB
      - ND_AUTOIMPORTPLAYLISTS=false
      - ND_BASEURL=/mg
      - ND_ENABLESTARRATING=false
      - ND_ENABLEGRAVATAR=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - musik_smb_mg:/music:ro
      - data:/data
    networks:
      - nw_proxy_traefik
    labels:
      - traefik.http.routers.navidrome-mg.rule=Host(`audio.XXXXXX.net`)&&PathPrefix(`/mg`)
      - traefik.enable=true
      - traefik.http.routers.navidrome-mg.tls=true
      - traefik.http.routers.navidrome-mg.tls.certresolver=resolver_letsencrypt
      - traefik.http.routers.navidrome-mg.entrypoints=entry_https
      - traefik.http.services.navidrome-mg.loadbalancer.server.port=4533
    ports:
      - "4533:4533"


######## Volumes ########
volumes:
  data:
  musik_smb_mg: # Verzeichnis in restic aus Backup ausnehmen!
    driver: local
    driver_opts:
      type: "cifs"
      o: "user=navidrome,password=XXXXXXXXXXXXX"
      device: "//192.168.2.36/musik/Musik"
######## Networks ########
networks:
  nw_proxy_traefik:
    external: true

```

### Additional information

![2021-06-14 13_38_33-Greenshot](https://user-images.githubusercontent.com/38253905/121887117-9eac5200-cd16-11eb-8ac9-de17a9dc0e2c.png)

![2021-06-14 13_40_08-Greenshot](https://user-images.githubusercontent.com/38253905/121886931-60af2e00-cd16-11eb-893e-15f335d3d2eb.png)

**Comment by quotengrote** [comment] 2021-06-14 11:48
After stopping and restarting the container the space is now free.

**Comment by quotengrote** [comment] 2021-07-14 13:15
Any News on that?

In this screenshot it shows the growing disk-space consumption till i restart the container.
![2021-07-14 15_14_41-Greenshot](https://user-images.githubusercontent.com/38253905/125628250-ec2e2deb-8925-41ef-9cba-4aa062dc6721.png)

**Comment by deluan** [comment] 2021-07-14 13:36
Sorry, but I fail to understand how it is even possible.... The only process I know could be writing to this file is a DHCP daemon, and it has nothing to do with Navidrome. This seems to be caused by some configuration in your environment. Is the `resolve.conf` file mounted by any other container/process? Can you check which processes have the file opened?

**Comment by quotengrote** [comment] 2021-07-14 15:15
Hi, thx for the answer.

At the moment it runs as it should. resolve.conf isnt opened anywhere.
`
/app # cat /etc/resolv.conf
search grote.lan
nameserver 127.0.0.11
options edns0 trust-ad ndots:0
`

**Comment by quotengrote** [comment] 2021-07-15 19:40
Hi, today it occured again.
The output of `lsof`, looks normal.

BUT...
it is the Logfile that Navidrome writes thats gets so big...(78GB)

and its XXX lines like these:

```
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.809666206Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.809818891Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.810026535Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.810201235Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.810378057Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.810546754Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.810704046Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.810873844Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.811044583Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.811234933Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.811464384Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.811721282Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.811927592Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.812087093Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.812274615Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.812469758Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.812668644Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.812849976Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.813031325Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.813204436Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.813454578Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.813680273Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.813920626Z"}
{"log":"time=\"2021-07-14T21:21:24Z\" level=warning msg=\"Skipping DirEntry\" error=\"readdirent /music/K/Keygen Music Pack - ScoRPioN2: no such file or directory\"\n","stream":"stderr","time":"2021-07-14T21:21:24.814124447Z"}
```

**Comment by quotengrote** [comment] 2021-07-15 20:54
If you need the complete log i can upload it, after rar'ing ist only 2GB big

**Comment by deluan** [comment] 2021-07-15 23:17
Ah, ok. That makes more sense, even though I don't know what is the problem. This is the same issue as #1164. Please close this and follow that one to get updates on the issue.

**Closed** 2021-07-16 07:05 UTC
Labels: bug
