### ISSUE TITLE
0.49.2 could not start after update on docker

### ISSUE THREAD

**Issue by eskiiom** [navidrome/navidrome#2172] opened 2023-02-12 20:26 UTC
### Description

Hello,

I've just updated the docker image with recreate option on portainer.
The container has sucesfully updated for 0.49.1 to 0.49.2 but now in the logfile I have the following message, and the app is not working anymore

`time="2023-02-12T20:19:03Z" level=fatal msg="Failed to apply new migrations" error="ERROR 20230209181414_change_image_files_list_separator.go: failed to run Go migration function func(*sql.Tx) error: sql: Scan error on column index 1, name \"image_files\": converting NULL to string is unsupported"

                          Version: 0.49.2 (3cd934ab)`

I don't think I have missed something, I've tried to recreate it again but it's still stuck

Debug file [attached]
[_navidrome_navidrome_1_logs.txt](https://github.com/navidrome/navidrome/files/10717202/_navidrome_navidrome_1_logs.txt)

Thanks

**Comment by dweymouth** [comment] 2023-02-12 20:31
Likely a duplicate of #2168

**Comment by deluan** [comment] 2023-02-12 20:31
Duplicate of #2168. A fix will be released hopefully EOD

**Closed** 2023-02-12 20:31 UTC
Labels: bug

**Comment by eskiiom** [comment] 2023-02-12 20:33
correct ! my bad @deluan 
I looked for opened issues and didn't think of checking closed ones sorry !
