### ISSUE TITLE
[Bug]: Updating playlists takes a long time

### ISSUE THREAD

**Issue by alexandrutirdea** [navidrome/navidrome#2706] opened 2023-12-15 10:41 UTC
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.2

### Current Behavior

Since the update to version 0.50 I have noticed that a library scan takes up to two hours due to how slow the playlist updates are. 

### Expected Behavior

A shorter scan time as it was before version 0.50

### Environment

```markdown
- OS: Debian 12 Bookworm
```

### How Navidrome is installed?

Docker

### Configuration

```toml
ND_SCANSCHEDULE: "0"
      ND_LOGLEVEL: "info"
      ND_BASEURL: "https://navidrome.xxxx.yy"
      ND_ENABLEDOWNLOADS: "true"
      ND_LASTFM_ENABLED: "false"
      ND_SESSIONTIMEOUT: 24h
      ND_COVERARTPRIORITY: "embedded, cover.*, folder.*"
      ND_AUTOIMPORTPLAYLISTS: "true"
      ND_AUTHREQUESTLIMIT: 3
      ND_AUTHWINDOWLENGTH: "20s"
      ND_SCANNER_EXTRACTOR: "ffmpeg"
      ND_ENABLEUSEREDITING: "true"
      ND_ENABLETRANSCODINGCONFIG: "false"
      ND_IMAGECACHESIZE: 0
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by starkgate** [comment] 2023-12-15 11:27
Noticed the same issue, the Symfonium scan times out because of how slow the responses are (about 2 minutes for 1000 songs). Here is today's navidrome log: [logs.txt](https://github.com/navidrome/navidrome/files/13684595/logs.txt)

Excerpt from the Symfonium log:
```
10:43:30.719 P:Verbose T:SubsonicLogger
<-- [979] 200 OK http://192.168.3.231:4533/rest/search3.view?query=%22%22&songOffset=7000&songCount=1000&albumOffset=0&albumCount=0&artistOffset=0&artistCount=0&u=REDACTED&t=REDACTED&s=REDACTED&v=1.13.0&c=Symfonium&f=json (116861ms, unknown-length body)
```

**Comment by deluan** [comment] 2023-12-15 12:47
@alexandrutirdea: yes, scan times in 0.50.x are longer than in previous versions. The scanner is being reworked right now, to add new features and to make it faster. But, I'd like to understand why do you think the issue is with updating playlists? Can you provide debug logs for it?

@starkgate: You are talking about a different issue. Symfonium does not "scan", it syncs with Navidrome. The sync is currently [slow with large libraries](https://support.symfonium.app/t/progress-percentage-bar-or-log-for-library-sync/2191/19), but this was [fixed](#2655) in `master` and the fix will be in the next release. 

If that is not your issue, please open a new ticket here with a debug log (the one you provided has log_level=info, not much useful)

**Comment by starkgate** [comment] 2023-12-15 13:05
> @starkgate: You are talking about a different issue. Symfonium does not "scan", it syncs with Navidrome. The sync is currently [slow with large libraries](https://support.symfonium.app/t/progress-percentage-bar-or-log-for-library-sync/2191/19), but this was [fixed](#2655) in `master` and the fix will be in the next release.
> 
> If that is not your issue, please open a new ticket here with a debug log (the one you provided has log_level=info, not much useful)

My bad, I thought this sounded similar to my issue. I will open a new ticket once I can reproduce with debug logs.

**Comment by deluan** [comment] 2023-12-15 13:11
> My bad, I thought this sounded similar to my issue. I will open a new ticket once I can reproduce with debug logs.

No problem. If you can, check if the issue is related to what I linked above. You can also try the `develop` version to check if the issue is resolved for you before any further investigation. Just remember to backup your `navidrome.db` file, if you decide to go back to your current version.

**Comment by starkgate** [comment] 2023-12-15 13:14
> > My bad, I thought this sounded similar to my issue. I will open a new ticket once I can reproduce with debug logs.
> 
> No problem. If you can, check if the issue is related to what I linked above. You can also try the `develop` version to check if the issue is resolved for you before any further investigation. Just remember to backup your `navidrome.db` file, if you decide to go back to your current version.

I restarted 0.50.2 with log level debug, and couldn't reproduce the issue. If it happens again I will open a ticket, but for now I guess it can be considered 'fixed'.

**Comment by alexandrutirdea** [comment] 2023-12-15 15:01
[debug.txt](https://github.com/navidrome/navidrome/files/13686560/debug.txt)

I have attached the debug logs of the latest scan here. The actual scan for new music was fast, but then it needed almost 100 minutes to sync the m3u playlists present in the music directory.

**Comment by arg274** [comment] 2024-03-09 08:37
This bug is most probably still present. The music quick scan on 60k files finished in a few minutes but the playlist updates are nowhere to be seen in 30 minutes (and the scan indicator is still circling).

**Comment by deluan** [comment] 2024-09-18 21:36
Hey @alexandrutirdea, sorry for not replying sooner, I was trying to focus on the new scanner, and hopefully it would solve this, but as you can see it is not done yet :(

I was looking into your logs, and I can see you have pretty big playlists. Some examples:
```
name="Always worth a spin" numTracks=8300                - 7 mins
name="EPs and short albums" numTracks=3145               - 6 mins
name="Last played more than 1 year ago" numTracks=8827   - 13 mins 
name="Last played more than 2 years ago" numTracks=7982   - 12 mins
```

I'll try to optimize it in the new scanner, but based on the name of the playlists, I'm assuming they are auto-generated by an external app, is that correct? Maybe you can replace them with [Smart Playlists](https://github.com/navidrome/navidrome/issues/1417), that would make them be imported faster. Ex for the "Last played more than 1 year ago":
```jsonc
{
  "name": "Last played more than 1 year ago",
  "comment": "Last played more than 1 year ago",
  "all": [
    {"notInTheLast": {"lastPlayed": 365}}
  ],
  "sort": "lastPlayed",
  "order": "desc"
  // , "limit": 100 <- You can even add a limit to make it even faster
}
```

@arg274 
> The music quick scan on 60k files finished in a few minutes

Are your files on a network drive? A quick scan for 60K should take a few seconds, not minutes.

**Comment by deluan** [comment] 2024-09-18 23:13
I did some tests locally. With a test library of 4979 songs:

Normal Playlist:
```
elapsed=4.99s name="All M3U" numTracks=4979
```
Smart Playlist:
```
elapsed=31.9ms name="All NSP" numTracks=4979
```

As you can see the difference is huge! Try leveraging Smart Playlists

**Comment by deluan** [comment] 2024-09-19 00:18
Ok, I pushed a change to optimize it. Normal playlists have to check each file for their presence in the DB and Smart playlists only execute one query.

I changed the code for normal playlists to batch the queries, 400 file per query, so I was able to get the example above to ~700ms. Better, and I'm not sure I'll be able to improve it even more.

Let me know if you can test your playlists with the [latest build](https://nightly.link/navidrome/navidrome/workflows/pipeline/master)

**Comment by alexandrutirdea** [comment] 2024-09-22 07:07
Hello! I have tested with the latest version and I am happy to report that it is working as I wanted. Thanks a lot for your efforts! As for the suggestion regarding using the smart playlist functionality, I am too deep in my relationship with MusicBee and how it manages my files using my last.fm data to create those playlists.

**Closed** 2024-09-22 15:11 UTC
Labels: enhancement
