### ISSUE TITLE
[Bug]: Linux Mismatch in the latest update

### ISSUE THREAD

**Issue by tamimology** [navidrome/navidrome#2628] opened 2023-11-17 22:27 UTC
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.0

### Current Behavior

navidrome The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
The container is showing unhealthy as well even after starting. However, I can still access it

![image](https://github.com/navidrome/navidrome/assets/90429593/bfe1980f-09ac-407c-af36-3e9a4cda1587)

### Expected Behavior

did not see this issue in the previous release

### Environment

```markdown
- OS: Synology Diskstation 6.2.4
- Browser: Chrome 119.0.6045.159 on LinuxMint
- Client: Substream (latest version)
```

### How Navidrome is installed?

Docker

### Configuration

```toml
navidrome:
    container_name: navidrome
    restart: always
    environment:
      ND_SCANSCHEDULE: 1h
      ND_AUTHREQUESTLIMIT: 5
      ND_AUTHWINDOWLENGTH: 30s
      ND_LASTFM_ENABLED: false
      ND_LISTENBRAINZ_ENABLED: false
      ND_ENABLEEXTERNALSERVICES: false
    volumes:
      - $PERSIST/navidrome:/data
      - $MEDIA_PATH/Music:/music:ro
    ports:
      - 4533:4533
    labels: 
      # autoheal: true
      monocker.enable: true
    user: 1035:$PGID
    image: 'deluan/navidrome:latest'
```

### Relevant log output

```shell
2023-11-17T22:21:34.032141230Z  _   _             _     _
2023-11-17T22:21:34.034547048Z | \ | |           (_)   | |
2023-11-17T22:21:34.034775459Z |  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
2023-11-17T22:21:34.036127408Z | . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
2023-11-17T22:21:34.036373461Z | |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
2023-11-17T22:21:34.036553411Z \_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
2023-11-17T22:21:34.036720792Z                           Version: 0.50.0 (fee0f40a)
2023-11-17T22:21:34.038002016Z 
2023-11-17T22:21:34.045034726Z time="2023-11-17T22:21:34Z" level=info msg="All external integrations are DISABLED!"
2023-11-17T22:21:34.114523776Z time="2023-11-17T22:21:34Z" level=info msg="goose: no migrations to run. current version: 20230616214944\n"
2023-11-17T22:21:34.294850393Z time="2023-11-17T22:21:34Z" level=info msg="Starting signaler"
2023-11-17T22:21:34.295070439Z time="2023-11-17T22:21:34Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music
2023-11-17T22:21:34.295203836Z time="2023-11-17T22:21:34Z" level=info msg="Starting scheduler"
2023-11-17T22:21:34.295308922Z time="2023-11-17T22:21:34Z" level=info msg="Creating Image cache" maxSize="100 MB" path=/data/cache/images
2023-11-17T22:21:34.295435304Z time="2023-11-17T22:21:34Z" level=info msg="Scheduling periodic scan" schedule="@every 1h"
2023-11-17T22:21:34.295551137Z time="2023-11-17T22:21:34Z" level=info msg="Setting Session Timeout" value=24h
2023-11-17T22:21:34.295661046Z time="2023-11-17T22:21:34Z" level=info msg="Login rate limit set" requestLimit=5 windowLength=30s
2023-11-17T22:21:34.295779815Z time="2023-11-17T22:21:34Z" level=info msg="Found ffmpeg" path=/usr/bin/ffmpeg
2023-11-17T22:21:34.295890904Z time="2023-11-17T22:21:34Z" level=info msg="Mounting Native API routes" path=/api
2023-11-17T22:21:34.296050786Z time="2023-11-17T22:21:34Z" level=info msg="Creating Transcoding cache" maxSize="100 MB" path=/data/cache/transcoding
2023-11-17T22:21:34.296173413Z time="2023-11-17T22:21:34Z" level=info msg="Mounting Subsonic API routes" path=/rest
2023-11-17T22:21:34.296284555Z time="2023-11-17T22:21:34Z" level=info msg="Mounting Public Endpoints routes" path=/share
2023-11-17T22:21:34.296405136Z time="2023-11-17T22:21:34Z" level=info msg="Mounting WebUI routes" path=/app
2023-11-17T22:21:34.296515090Z time="2023-11-17T22:21:34Z" level=info msg="Finished initializing cache" cache=Transcoding elapsedTime=25.5ms maxSize=100MB
2023-11-17T22:21:34.296633961Z time="2023-11-17T22:21:34Z" level=info msg="----> Navidrome server is ready!" address="0.0.0.0:4533" startupTime=247.7ms tlsEnabled=false
2023-11-17T22:21:54.966576800Z time="2023-11-17T22:21:54Z" level=info msg="Finished initializing cache" cache=Image elapsedTime=20.85s maxSize=100MB
```

### Anything else?

![image](https://github.com/navidrome/navidrome/assets/90429593/0d71e71a-801f-4f42-8522-f01ac2952cab)

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by Theta-Dev** [comment] 2023-11-17 22:41
I have just noticed that for some reason the latest version was only published for the amd64 architecture on DockerHub.

The GHCR image seems to be available for all architectures, though, so maybe they just want you to switch: `ghcr.io/navidrome/navidrome:latest`

**Comment by deluan** [comment] 2023-11-17 23:18
Duplicate of https://github.com/navidrome/navidrome/issues/2621

Yes, there was an issue when publishing the new image to Docker Hub, but it was successfully pushed to GHCR, as mentioned by @sprnza .

I was able to manually fix the AMD64 image, but the ARM ones are still broken. The issue was already fixed and next release will be pushed normaly to both repositories.

**Closed by deluan** 2023-11-17 23:18 UTC
Labels: bug, duplicate
