### ISSUE TITLE
avahi-daemon error

### ISSUE THREAD

**Issue by un99known99** [navidrome/navidrome#1340] opened 2021-09-11 20:37 UTC
### Description
regularyly all 5-6 mins following records are showing up in syslog:

Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_normalize_name() failed.
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_key_new() failed.
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_normalize_name() failed.
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_key_new() failed.
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_normalize_name() failed.
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_key_new() failed.

### Expected Behaviour

no avahi error entries

### Steps to reproduce

play/stream music from local pi-device

### Platform information

 - Navidrome version: v.0.45.1
 - Browser and version: Firefox 92.0 (64bit)
 - Operating System: raspberian OS (Linux 5.10.60-v7+ armv7l)

### Additional information

Any other information that may be relevant or give context to the problem.

 - Logs
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_normalize_name() failed.
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_key_new() failed.
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_normalize_name() failed.
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_key_new() failed.
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_normalize_name() failed.
Sep 11 22:12:14 raspberrypi avahi-daemon[382]: avahi_key_new() failed.

**Comment by certuna** [comment] 2021-09-20 11:58
I see this error message posted in a lot of Debian forums/bugtrackers, are we sure this is has any relation with Navidrome?

**Comment by deluan** [comment] 2021-09-20 23:04
Yes, based on the discussion on Discord, looks like it was caused by something else, not Navidrome. Will close this but feel free to reopen if you have any remaining concerns.

**Closed by deluan** 2021-09-20 23:04 UTC
Labels: bug
