### ISSUE TITLE
[Bug]: About sorting artists with Chinese names (or non-English? )

### ISSUE THREAD

**Issue by xdjohn99** [navidrome/navidrome#2691] opened 2023-12-07 05:33 UTC
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

[0.50.1](https://github.com/navidrome/navidrome/releases/tag/v0.50.1) (f69c27d1)

### Current Behavior

For me, this situation occurred with artists with Chinese names, on the artist page of the website. 

The Chinese artist sorting is neither based on Mandarin Pinyin nor artistsort-tag.

**It seems to be sorted based on the Unicode encoding:**

![issue](https://github.com/navidrome/navidrome/assets/102330218/1bd1e413-bb3c-4171-9807-ccafc76bec58)

(I'm not sure about if it's a bug or it could be due to my mishandling)

### Expected Behavior

If it can be sorted by the tag, that would be great.

### Steps To Reproduce

Open the web and click on the artist page.

### Environment

```markdown
Win 10 Navidrome service
Chrome 119.0.6045.200
```

### How Navidrome is installed?

Package

### Anything else?

https://github.com/navidrome/navidrome/issues/643
https://github.com/navidrome/navidrome/issues/2188

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by certuna** [comment] 2023-12-07 18:47
I guess this could be done with `COLLATE LOCALIZED` in SQLite, like mentioned here: https://github.com/tekartik/sqflite/discussions/942

@deluan do you know if it would be hard to implement?

**Comment by deluan** [comment] 2023-12-07 23:11
> I guess this could be done with COLLATE LOCALIZED in SQLite, like mentioned here: https://github.com/tekartik/sqflite/discussions/942

I'll experiment with this, but maybe a solution could be having a flag to make Navidrome use the `Sort` tags instead of the current logic of using the normal tags with articles stripped. This would also fix #643, right?

**Comment by deluan** [comment] 2023-12-07 23:32
> I guess this could be done with COLLATE LOCALIZED in SQLite, like mentioned here: [tekartik/sqflite#942](https://github.com/tekartik/sqflite/discussions/942)

I just tried and remembered why I haven't done this before: It requires an external plugin: https://stackoverflow.com/questions/29122866/getting-collate-localized-unicode-on-non-android-sqlite

I think I'll go with the `Sort` tags solution. Let me know if you have any concerns.

**Comment by deluan** [comment] 2023-12-10 02:32
The solution is to use Sort tags, which makes this a duplicate of #643. Closing now and please follow that issue for updates.

**Closed by deluan** 2023-12-10 02:32 UTC
Labels: bug, triage
