### ISSUE TITLE
[Bug]: Track metadata from internet radio stream not shown

### ISSUE THREAD

**Issue by reitzig** [navidrome/navidrome#3168] opened 2024-07-28 14:21 UTC
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

Playing [Radio Bob!](http://streams.radiobob.de/bob-national/mp3-192/mediaplayer), Navidrom shows only the station name instead of artist and title:

![image](https://github.com/user-attachments/assets/f397b1c5-9d5f-464a-8784-c1108bd9b6ae)

The stream seems to provide those data; the VLC shows artist and title for that same stream:

![image](https://github.com/user-attachments/assets/0aa7dfc6-6f1c-4a6d-b8bb-b15006d2e67c)

Symfonium also shows artist and title after importing the radio from Navidrome; not sure whether it streams _through_ Navidrome or directly, though.

### Expected Behavior

Navidrom should detect and display whatever metadata is available from the radio stream.

If set up for scrobbling, it should also scrobble detected tracks.

### Steps To Reproduce

1. Add the [radio stream](http://streams.radiobob.de/bob-national/mp3-192/mediaplayer) through the web UI
2. Hit play

### Environment

```markdown
- OS: Windows 11 / Ubuntu 18.04
- Browser: Firefox 128
- Client: Navidrome Web UI
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = "/media/data/Musik/"

LastFM.Enabled = true
LastFM.ApiKey = "somehex"
LastFM.Secret = "otherhex"
```

### Relevant log output

There do not seem to be any log messages when playing a radio (on `info` level, at least).

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by reitzig** [comment] 2024-07-28 23:47
It seems that this particular radio, at least, utilizes "Now playing":

![image](https://github.com/user-attachments/assets/cdf80bf0-9be9-4731-91e0-35d122cc7af7)
(screenshot of VLC)

**Comment by kgarner7** [comment] 2024-08-02 04:07
This is not a bug, so much as a missing feature. The radio you are using most likely uses Icecast metadata. You would need something like https://github.com/eshaz/icecast-metadata-js to get the metadata in js

**Comment by Szeraax** [comment] 2024-11-09 19:12
I'm going to go ahead and close this since its not a bug. Please feel free to create a new feature request for showing additional data.

**Closed by Szeraax** 2024-11-09 19:12 UTC
Labels: bug
