### ISSUE TITLE
Scanner misses media files that start with a period

### ISSUE THREAD

**Issue by ggendel** [navidrome/navidrome#2060] opened 2022-12-29 00:25 UTC
### Description

The scanner skips over media files that start with a period.  For example, these songs:
.45.mpg
...One More Time.flac

### Expected Behaviour

These songs should be imported into the database.

### Steps to reproduce

1. Add or rename a song so it name starts with a "."
2. Run a scan
3. The song is missing in the database.
4. This can also be verified by importing a playlist with that file in it.  The scanner produces a missing file error.

### Platform information

 - Navidrome version: 
 - Browser and version: Various browsers and Subsonic apps
 - Operating System: Opensuse Leap 42.5

### Additional information

Any other information that may be relevant or give context to the problem.

 - Screenshots (if applicable)?
 - Logs? 
 WARN[0206] Path in playlist not found                    error="data not found" path="/music/\"Artists/The Baseballs/2016 - Hit Me Baby/...Baby One More Time.flac\"" playlist=gary
WARN[0206] Path in playlist not found                    error="data not found" path="/music/\"Artists/Doom Unit/III (2013)/.45.mp3\"" playlist=gary
 - Client used? N/A

**Comment by deluan** [comment] 2022-12-30 16:48
Thanks for using Navidrome. This is expected behaviour, basically because in Unix based OSes files starting with `.` are considered "hidden" files. In macOS it is even worse, as it may create files like `._02 Invisible.mp3` for each file you have in a given folder.

The only solution for this is to rename the files. Will close this as expected behaviour, but feel free to chime in if you have any concerns.

**Closed by deluan** 2022-12-30 16:48 UTC
Labels: bug

**Comment by ggendel** [comment] 2022-12-31 12:53
Thanks. I already had implemented the workaround and agree with your assessment.  I just wanted to document it.  Perhaps we should note this feature in the documentation?
