### ISSUE TITLE
[Bug]: Folders appearing as changed when they are not

### ISSUE THREAD

**Issue by SteveDinn** [navidrome/navidrome#3282] opened 2024-09-18 19:16 UTC
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.53.1 (1ba390a7)

### Current Behavior

I was watching my logs after updating my docker container to the newest 0.53.1 release.
I added a few new albums, and I noticed in my logs that the same three folders (the new albums I added) were getting detected as changed every 5 minutes (my scan interval).

I assume this is a problem with 0.53 or 0.53.1 because only the folders from albums I have added post-upgrade are showing up like this.

There are no errors though :)

### Expected Behavior

Folders would only be detected when they had actually changed.

### Steps To Reproduce

1. Run Navidrome 0.53.1
2. Add one or more new albums
3. Watch logs to see those albums' folders get processed as changed several times.

### Environment

```markdown
- OS:Debian 11 (via docker-compose)
- Browser: Firefox, but I think this is irrelevant(?)
- Client: web
```

### How Navidrome is installed?

Docker

### Configuration

```toml
docker-compose.yml:
-------------------
version: "3"
services:
  app:
    image: deluan/navidrome
    user: "1006:1002"
    restart: "no"
    ports:
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples:
      ND_CONFIGFILE: "/data/navidrome.yml"
    volumes:
      - "./data:/data"
      #- "./cache:/cache"
      - "/mnt/mediasonic/media/music/Steve:/music:ro"

navidrome.yml:
--------------
ScanSchedule: "@every 5m"
LogLevel: info
BaseUrl: ""
EnableSharing: true
#EnableTranscodingConfig: true
TranscodingCacheSize: 2Gib
ImageCacheSize: 200Mib
DevActivityMenu: true
DevActivityPanel: true
SessionTimeout: 999h
PlaylistsPath: "playlists"
```

### Relevant log output

```shell
Blank lines are mine, for clarity:

app_1  | time="2024-09-18T18:56:05Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Chad VanGaalen/Light Information" elapsed=40.7ms updated=0
app_1  | time="2024-09-18T18:56:05Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Demi Lovato/REVAMPED" elapsed=23.1ms updated=0
app_1  | time="2024-09-18T18:56:05Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Oasis/Definitely Maybe" elapsed=18.9ms updated=0
app_1  | time="2024-09-18T18:56:05Z" level=info msg="Finished processing Music Folder" added=0 deleted=0 elapsed=964.5ms folder=/music playlistsImported=0 updated=0

app_1  | time="2024-09-18T19:01:05Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Chad VanGaalen/Light Information" elapsed=28.2ms updated=0
app_1  | time="2024-09-18T19:01:05Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Demi Lovato/REVAMPED" elapsed=19.7ms updated=0
app_1  | time="2024-09-18T19:01:05Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Oasis/Definitely Maybe" elapsed=17.4ms updated=0
app_1  | time="2024-09-18T19:01:05Z" level=info msg="Finished processing Music Folder" added=0 deleted=0 elapsed=929.1ms folder=/music playlistsImported=0 updated=0

app_1  | time="2024-09-18T19:06:05Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Chad VanGaalen/Light Information" elapsed=53.4ms updated=0
app_1  | time="2024-09-18T19:06:05Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Demi Lovato/REVAMPED" elapsed=14.9ms updated=0
app_1  | time="2024-09-18T19:06:05Z" level=info msg="Finished processing changed folder" deleted=0 dir="/music/Oasis/Definitely Maybe" elapsed=23.5ms updated=0
app_1  | time="2024-09-18T19:06:05Z" level=info msg="Finished processing Music Folder" added=0 deleted=0 elapsed=939.2ms folder=/music playlistsImported=0 updated=0
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment] 2024-09-18 21:11
I was not able to reproduce it here. Can you please verify if the timestamp of the folders (or _any_ file inside it) are not in the future?

**Comment by SteveDinn** [comment] 2024-09-18 21:39
Just verified that the most recent file of all was dated today at 14:09 UTC, hours before these log entries.

HOWEVER, I restarted the container, and it hasn't happened since, even with a manual quick scan.

Maybe just keep an eye on it?

**Comment by deluan** [comment] 2024-09-18 21:42
> Maybe just keep an eye on it?


Yes, please. I'll keep it open, but please report back or close this if you don't see any issues in the next couple of weeks. Thanks!

**Comment by SteveDinn** [comment] 2024-09-23 18:25
It happened again in the same manner after upgrading to 0.53.2: After I upgraded, I added an album, and it seems to see the folder as changed on every scan.

Furthermore, I can reproduce the issue directly after I delete and re-create the container (as I had been doing for the upgrades), but NOT when I simply restart the container. Is there a difference between these for Navidrome?

**Comment by Tolriq** [comment] 2024-09-23 18:37
@deluan That sounds like a good candidate for https://support.symfonium.app/t/high-data-activity-but-nothing-shown-in-download-queue/5247 no ? This would trigger new album art id?

**Comment by SickProdigy** [comment] 2024-09-23 20:42
> It happened again in the same manner after upgrading to 0.53.2: After I upgraded, I added an album, and it seems to see the folder as changed on every scan.
> 
> Furthermore, I can reproduce the issue directly after I delete and re-create the container (as I had been doing for the upgrades), but NOT when I simply restart the container. Is there a difference between these for Navidrome?

Are the timestamps in the future? I've had similar issue with plex and always the timestamp. Stopping a container can do weird things sometimes if it doesn't safely stop all processes first.

**Comment by SteveDinn** [comment] 2024-09-23 20:56
No @deluan got me to check that the first time. All timestamps are in the past, and exactly what they should be.

**Comment by deluan** [comment] 2024-09-23 23:04
> ```shell
> msg="Finished processing changed folder" deleted=0 dir="/music/Demi Lovato/REVAMPED" elapsed=14.9ms updated=0
> ```

@Tolriq 
I don't think the IDs would change in this case, as you can see from the logs that there was no file updated in the DB.

@SteveDinn I'll try to reproduce again and let you know. In the meantime, can you try changing the log level to `trace`, and send me the log of just the scan part? Thanks.

**Comment by Hermanio** [comment] 2024-09-25 05:18
I've observed similar issues on my instance, running version 0.53.2 (3910e77a), Docker.

I have a script that updates a bunch of playlists (.m3u files get regenerated). Navidrome usually picks up those changes with a quick scan. Scan schedule is set to every 1 minute (the default). 

With 0.53.2, the scans are very CPU intensive, as if Navidrome just started up with a fresh install and is reprocessing everything.

Does not occur on 0.52.5. 

What I can put together from logs is that with 0.52.5, I see "No changes found in Music Folder" with every subsequent scan. 
With 0.53.2, **_every_** scan is accompanied with "Processing changed folder". 

I did my best to reproduce the issue on a clean build, I've attached the test setup (logs, Docker Compose files, Navidrome data itself). Only thing missing is the actual music folder. Navidrome instance username/password is `admin`.

I set up 0.53.2, added one folder containing music and a .m3u file. 
I let Navidrome scan it.
Then I removed one entry from the .m3u file using a text editor and saved. 
Then I let Navidrome operate for a few minutes, letting it do a few scans.

I then stopped the container and started Navidrome on 0.52.5, repeating the same steps. 

If you copy over a folder containing music files and .m3u playlist to `/music`, and if you modify the .m3u file after Navidrome has made the initial full scan, you should be able to reproduce the issue. If not, then feel free to ask for more details, I'll do my best to help.
 
[deluan-navidrome-issue3282.zip](https://github.com/user-attachments/files/17125317/deluan-navidrome-issue3282.zip)

**Comment by deluan** [comment] 2024-09-25 13:19
Thanks @Hermanio, I think I know what is happening. I'll try to get a fix for it this week.

**Comment by deluan** [comment] 2024-09-25 21:13
Fix is here: the binary will soon be attached to this issue as a comment, and if you are using docker you can try it with the tag `deluan/navidrome:pr-3313`

This will be part of this weekend's release

**Comment by Hermanio** [comment] 2024-09-26 06:17
I ran my actual Navidrome setup on `deluan/navidrome:pr-3313` and can't reproduce the issue any longer. Thank you!

**Closed** 2024-09-26 10:16 UTC
Labels: bug, go

**Comment by SteveDinn** [comment] 2024-09-28 00:18
Fixed for me as well! Thanks!
