### ISSUE TITLE
Add an Album Artist column for the Albums table view

### ISSUE THREAD

**Issue by infinitejones** [navidrome/navidrome#1876] opened 2022-09-19 06:15 UTC
### Is your feature request related to a problem? Please describe.

When compilation/Various Artists albums are displayed in the Albums table view,  the Artist column shows the Artist of one of the tracks from the album. This is confusing, because it makes it look like the whole album is by that Artist, whereas actually the Artist is likely to be just one of many contributors.

### Describe the solution you'd like

It would be preferable if it was possible to show the Album Artist column as well as or instead of the Artist column. That way, for an appropriately-tagged compilation/Various Artists album, the Album Artist column in the Table view would correctly reflect Various Artists.

Please note that this does behave correctly/as intended in the Grid view, for a given compilation/Various Artists album. Screenshots:

![Various Artists correct](https://user-images.githubusercontent.com/5801868/190959020-7e988e67-c608-4667-b1f9-2332a6c17b3d.png)

![Various Artists incorrect](https://user-images.githubusercontent.com/5801868/190959007-00bbb2e7-81be-4844-a978-c43b1916f06b.png)

### Describe alternative solutions that would also satisfy this problem

A column on the Table View that indicates whether the album is tagged as a Compilation would almost provide an alternative, but it's not as clear and straightforward as if the Table just displays Album Artist instead of Artist.

### Additional context

Either way, this would require correct tagging of the Compilation artist, but I'd argue that's the responsibility of the user rather than the developer and therefore edge cases might not need to be looked at too closely.

**Comment by metalheim** [comment] 2022-09-20 11:30
Hi. we talked about this briefly on reddit.
I am pretty sure that it *should* display "Various artists" in the list view as well and it's a bug. I would bet that it was that way in previous releases and appeared one day.

Anyways thanks for opening the issue. Maybe deluan can share an opinion if its "a bug or a feature"™

**Comment by deluan** [comment] 2022-09-29 20:56
Thanks for reporting. This has two parts:
- A bug, that is a duplicate of #1626. I just pushed a fix for this and it will be available in the next release.
- A feature request (add artist as an column option in table view)

The feature request doesn't make too much sense, as it would show the "random" value you see now in compilations. And in normal albums, it would duplicate the name from albumArtist.

I'll close this (as the bug is fixed), but feel free to reply with any concerns.

**Closed by deluan** 2022-09-29 20:56 UTC
Labels: enhancement
