### ISSUE TITLE
UI slow with big Playlists

### ISSUE THREAD

**Issue by pagdot** [navidrome/navidrome#621] opened 2020-11-13 09:56 UTC
When opening a playlist with a few hundred (~600 in my case) entries the UI is really slow when loading the playlist or updating the UI.

**Comment by deluan** [comment] 2020-11-13 14:37
Thanks for creating the issue. Will take a look at ways to optimize it

**Comment by deluan** [comment] 2020-11-27 01:52
Hey, I'm doing some refactoring in the playlist view while migrating to the newest version of React-Admin, can you try this new version?

Binaries are available here: https://github.com/deluan/navidrome/suites/1569196857/artifacts/28258034
For the docker image, use the label `deluan/navidrome:pr-667`

There's still work to do to make it better, but I think this new version will be an improvement.

**Comment by pagdot** [comment] 2020-11-27 16:12
It's much better now. Rendering when loading a playlist and clicking on play/next still takes a few seconds but much better than before :)

**Comment by deluan** [comment] 2020-11-27 16:18
Great! The main issue here is that, as the playlist gets bigger, React has a hard time to render all components in the page. The solution is to paginate the playlist, at least while I don't implement infinite scrolling, that would be the definitive solution. 

Will keep this open to track the pagination implementation

**Comment by 999eagle** [comment] 2021-04-02 20:10
Just to add to this: I have a playlist with 5775 songs and it's impossible to load. On my laptop it just loads for a few minutes until the tab crashes because it's out of memory. Firefox was using about 8 GB of memory at this point.

**Comment by deluan** [comment] 2021-04-03 01:09
Hey @999eagle thanks for the feedback. To be totally honest, I completely forgot about this... Will see if anything can be done before next release.

**Comment by RitikPandey1** [comment] 2021-04-03 13:12
Hey @deluan, I'd like to work on this

**Comment by deluan** [comment] 2021-04-03 16:51
Hey @999eagle, can you try with this build: https://github.com/navidrome/navidrome/suites/2413363545/artifacts/51439584
If you are using Docker, let me know and I'll make an image available.

**Comment by 999eagle** [comment] 2021-04-03 16:53
I'm using Docker, so if you could build a Docker image that'd be great.

**Comment by deluan** [comment] 2021-04-03 17:38
@999eagle Sure: you can use the tag `deluan/navidrome:pr-970`. Please give feedback 👍🏼

**Comment by 999eagle** [comment] 2021-04-03 17:44
@deluan @RitikPandey1 I've tested this now and the pagination works perfectly fine and my playlists loads pretty much instantly. The only problem is: If I click on Play or Shuffle, only the songs on the current page are added to the play queue making playlists a bit useless.

**Comment by 999eagle** [comment] 2021-04-03 17:45
Oh and another thing: Going to the last page and then increasing the number of items per page shows only "No results found" with no way to go to another page or change the number of items per page.

**Comment by deluan** [comment] 2021-04-03 17:49
> The only problem is: If I click on Play or Shuffle, only the songs on the current page are added to the play queue making playlists a bit useless.

Hummm... yeah, that could be trickier.... @RitikPandey1, let me know if you want to tackle this and need some assistence.

> Going to the last page and then increasing the number of items per page shows only "No results found" with no way to go to another page or change the number of items per page.

@RitikPandey1 can you take a look at this, please?

**Comment by deluan** [comment] 2021-04-03 18:08
@999eagle Just keep in mind that actions that add more than 2000 tracks to the play queue are generally very slow, and can take several seconds to complete.

**Comment by 999eagle** [comment] 2021-04-03 18:10
Yeah that's not too big of a problem. I can wait a few seconds. It's just when displaying the playlist takes multiple minutes and requires about 6 GB RAM when it's becoming a problem.

**Comment by RitikPandey1** [comment] 2021-04-03 19:29
> Oh and another thing: Going to the last page and then increasing the number of items per page shows only "No results found" with no way to go to another page or change the number of items per page.

@deluan This bug is caused because `setPerPage`  function provided by `<ReferenceManyField>`  didn't set `page=1` while changing `perPage` prop. I've fixed the bug by wrapping `PlaylistSongs` component inside `<ListBase>`  .  `<ListBase>` put data in list provider and then `setPerPage` function work exactly same as it work on normal `<List>` component.
I've committed the changes in PR: #969, please review it.

**Comment by RitikPandey1** [comment] 2021-04-03 19:39
> > The only problem is: If I click on Play or Shuffle, only the songs on the current page are added to the play queue making playlists a bit useless.
> 
> Hummm... yeah, that could be trickier.... @RitikPandey1, let me know if you want to tackle this and need some assistance.

adding all playlist songs on queue while using pagination is not an easy task, I'd like to give it a shot! 
Yes @deluan, I need your help please provide me a direction.

**Comment by deluan** [comment] 2021-04-05 00:32
Hi @999eagle, the latest from `pr-970` should fix the issues you mentioned (except for the "Play Next" and "Play Later" buttons. Can you please try it out and give feedback?

**Comment by 999eagle** [comment] 2021-04-05 06:36
Okay pagination still works fine and playing or shuffling the entire playlist adds all tracks to the play queue. Or rather, the number of tracks displayed in the play queue is correct, but I haven't actually checked whether all tracks are displayed.
Between clicking "Play" or "Shuffle" and music actually starting I have a delay of about 10 to 20 seconds which is totally okay for the list of (by now) 5768 songs. For some reason, other Firefox tabs running in the same process lock up and Firefox becomes entirely unresponsive for those tabs while Navidrome is loading all songs, but once playback starts it's fine. This seems to be a Firefox problem though.

**Closed** 2021-04-05 22:21 UTC
Labels: good first issue, web ui

**Comment by deluan** [comment] 2021-04-05 22:25
Thanks for testing it out @999eagle, probably this "freezing" is caused by non-preemptive nature of JS, and this can be further improved by paginating the API call and processing one returned page at a time. I hope this becomes unnecessary with the Infinite Scroll, but if it becomes a hassle, feel free to reopen this issue.

**Comment by 999eagle** [comment] 2021-04-06 14:59
@deluan I've tried listening to music for a few hours today using Navidrome. I don't know if this is related to this issue or not, but I've noticed that a playlist restarts from the very first song when I try to "play next" a song. The song I want to play next is added to the play queue in the correct position, but the playlist immediately restarts from the first entry of the play queue.

**Comment by deluan** [comment] 2021-04-06 15:10
@999eagle It is not related to this issue. This is a known bug: https://github.com/navidrome/navidrome/issues/650, and unfortunately we currently don't have a quick fix or workaround for it. :(

**Comment by 999eagle** [comment] 2021-04-06 15:13
@deluan it happened while playing though, not while paused. The currently playing song was interrupted and playback immediately started from the beginning of the play queue for me. Should I add that as a comment to the mentioned issue?
