### ISSUE TITLE
keep scrobble data for statistics

### ISSUE THREAD

**Issue by sebmuc99** [navidrome/navidrome#1970] opened 2022-11-02 10:24 UTC
as user/admin running navidrome i don't wanna share my data with anyone (ex. lastFM etc.) but still wanna have a monthly statistic about artist/songs that i was listening to.

would be great to have a 
- frontend view with table and filter for year/month and selection of top X songs
- export scrobble data to CSV option
- erase option to keep database small

actually the scrobble data is not stored in the backend, just counter and last play date are updated, so i'm even not able to create such reports manually.

**Comment by andrewgdunn** [comment] 2023-01-18 16:05
Wanted to point out that [this project](https://github.com/krateng/maloja) is a self hosted viewer for listen statistics.

**Comment by deluan** [comment] 2023-01-18 16:35
Closing this as a duplicate of #714. Also, the solution should be using another dedicated tool like Maloja, mentioned by @andrewgdunn . Navidrome can send scrobbles to Maloja using the ListenBrainz API with a custom URL (#1774).

**Closed by deluan** 2023-01-18 16:35 UTC
Labels: enhancement
