### ISSUE TITLE
Previous Track button does not restart the current track

### ISSUE THREAD

**Issue by nicholas-robertson** [navidrome/navidrome#652] opened 2020-11-21 13:27 UTC
I know that this is probably behaving as intended, but 95% of players implement this button such that it will first restart playback of the currently playing track from the beginning rather than going strait to the previous track.

**Comment by deluan** [comment] 2020-11-22 00:11
Sorry, I accidentally close this from my cellphone. This is a limitation of the upstream [React Player project](https://github.com/lijinke666/react-music-player) 

I agree the current behaviour is not the most intuitive, and I suggest you open an issue with that project. I'll keep this open with a "blocked" label while we don't get this functionality provided by the React Player project

**Comment by aniketbiswas21** [comment] 2021-04-12 13:30
@deluan Is there any way we can retrieve the current playtime of the current song? Like, setting it to the `previous id` if the playtime is `0:00` and replaying the `current id` if it is not?

**Comment by aniketbiswas21** [comment] 2021-04-14 04:18
https://github.com/lijinke666/react-music-player/issues/347

@deluan Raised an issue in `react-jinke-music-player` regarding this. I do have a plan to solve this issue, but the problem is, I was not able to extend my logic onto the player, so raised an issue regarding this.

**Comment by aniketbiswas21** [comment] 2021-04-22 08:30
https://github.com/lijinke666/react-music-player/pull/359

@deluan I opened a PR on react-jinke-music-player. If that gets merged, we will be able to proceed with this :)

**Comment by aniketbiswas21** [comment] 2021-05-07 07:19
@deluan UPDATE: My pr got merged :smile: 

We will be able to proceed with this, once the new version releases.

I will make a separate pr as soon as the former release :)

**Closed** 2021-05-08 18:27 UTC
Labels: blocked
