### ISSUE TITLE
Remove empty albums

### ISSUE THREAD

**Issue by rohitgeddam** [navidrome/navidrome#937] opened 2021-03-29 14:38 UTC
### Description

I deleted a song from my music folder however the album is still listed in the UI

![album_empty](https://user-images.githubusercontent.com/48797475/112853462-80956500-90ca-11eb-9a4d-1e9a6610b938.png)

![empty_album](https://user-images.githubusercontent.com/48797475/112851618-c8b38800-90c8-11eb-985b-258ac08ba2ce.png)

***It shows``` 1 Song · 03:55 · 8.98 MB ``` but there is no song present since I deleted it from the music folder***

### Expected Behaviour

The UI must not list empty albums or show wrong information,
There are no songs in this album but it shows ``` 1 Song · 03:55 · 8.98 MB ```

### Steps to reproduce

1. Delete any song from your music directory.
2. open the navidrome frontend in browser.
3. your album might still be listed even after deleting the song from the music folder.

**Comment by jvoisin** [comment] 2021-03-29 14:50
This is working as intended.

The next time the scanner will run, it'll detect that the files have been removed. In the meantime, they'll still be displayed in the interface.

**Comment by deluan** [comment] 2021-03-30 02:13
Yes, @jvoisin is correct in that Navidrome should remove the album in the next scan. But this image shows a bug:
![empty_album](https://user-images.githubusercontent.com/48797475/112851618-c8b38800-90c8-11eb-985b-258ac08ba2ce.png)


You should never have empty albums showing in the UI... 

@rohitgeddam How is your library setup? Do you have files from different albums in the same folder? How big is your library?

Can you try to reproduce again? After removing the song, try forcing a quick scan (in the Activity Panel). What is the result? Is the album still showing?

**Comment by rohitgeddam** [comment] 2021-03-30 04:07
- library setup?
    - I have put all my songs directly in my root music folder
- Do I have files from different albums in the same folder? 
    - yes I have all songs at the root of my music folder
- How big is my Library?

   - It's pretty small about  ( < 50 )

- reproducing the same again?
  - I removed another song from my music folder and did a manual quick scan, but the empty album is still showing.

![empty-album2](https://user-images.githubusercontent.com/48797475/112932380-6ba4ea00-913b-11eb-9f96-3ec192b9107a.png)

**Comment by rohitgeddam** [comment] 2021-03-30 05:38
Not sure why it's showing up in the UI, I checked the  media_file table in the DB and the song has been removed from the DB. So I guess our scanner is doing its job well.
I think it's a UI problem, I even tried to hard refresh the page to make sure it's not cached on the frontend. but no luck.

**Comment by armedev** [comment] 2021-03-30 05:59
@rohitgeddam stop your server and try deleting the **./data/** and restart the server, I reproduced the issue and solved this issue by doing so.

@deluan maybe there is a problem in the DB updating while scanning the folders.

**Comment by rohitgeddam** [comment] 2021-03-30 06:10
@armedev I am afraid that we cannot just delete the data folder since it holds the SQLite DB, 
***Must be some other way to handle this***

**Comment by armedev** [comment] 2021-03-31 05:22
> @armedev I am afraid that we cannot just delete the data folder since it holds the SQLite DB,
> _**Must be some other way to handle this**_

Yes, I meant to say to delete data in the development mode to figure out where the bug is.
Maybe in my opinion the data in DB is not updating as expected.

**Comment by hellojaccc** [comment] 2022-08-20 12:20
This issue hasn't been fixed. Please take a look.

**Comment by voryzen** [comment] 2022-09-24 14:41
bump

**Comment by jvoisin** [comment] 2022-09-24 15:14
You must be new to Free Software. This (amazing) piece of software is made by people on their free time. They might, or might not fix this particular bug, at some point in the future. 

Complaining/bumping it won't make it fixed faster. In fact, it might have the exact opposite effect: "How dare the people giving me this piece of software for free not providing me with free support as well?". The best way to get this issue fixed is to do it yourself, and open a [pull request]( https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) to get it fixed for everyone.

**Comment by voryzen** [comment] 2022-09-24 15:17
> You must be new to Free Software. This (amazing) piece of software is made by people on their free time. They might, or might not fix this particular bug, at some point in the future.
> 
> Complaining/bumping it won't make it fixed faster. In fact, it might have the exact opposite effect: "How dare the people giving me this piece of software for free not providing me with free support as well?". The best way to get this issue fixed is to do it yourself, and open a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) to get it fixed for everyone.

No one asked your opinion, mate. Thanks for giving it, though; really appreciate it.

**Comment by deluan** [comment] 2022-09-25 00:21
This is a well known bug and it happens when all songs of your library are located in the root of the Music Folder, without any subfolder. The workaround is quite simple, instead of:
```
MusicFolder = /music

Files:
/music/01-song.mp3
/music/02-song.mp3
```
Just put your songs under a subfolder inside the Music Folder:
```
MusicFolder = /music

Files:
/music/folder/01-song.mp3
/music/folder/02-song.mp3
```

As the workaround is very simple, this ticket has very low priority.

@voryzen:
> No one asked your opinion, mate.

Not cool man. If you are posting a comment on an open source (read: "free") project and gets a reply from one of the maintainers, you should use the opportunity to start a conversation and be humble about it. It is ok to just say "I'd love to contribute, but I'm not a developer". 

Bumping old issues is an action normally not well-received by open source (read: "free") project maintainers, as it only causes noise and more unnecessary notifications. You should only add comments if you have something to add to the issue, like a workaround or document other situations where the bug happens, so it gives more insights about the problem. 

If you want to ask others about the issue or need help with it, or just want to join the conversation, you can do this using other communication channels, like our Discord server.

**Comment by voryzen** [comment] 2022-09-25 00:50
Hi @deluan,

Thanks for the explanation; has this workaround been documented somewhere?
A precursory search doesn't show anything. ( I acknowledge your comment in #868 )

I'm glad you provided some more information, now others that have this issue and are searching for a workaround, can find one.

I'm happy to assist in adjusting the docs, to reflect this workaround; maybe a few well placed admonitions? What are your thoughts here?

**Comment by deluan** [comment] 2022-10-01 03:14
Thanks for the PR, I'll take a look. I'll close this as we now have a documented (here and soon in the FAQ) workaround, and this will be fixed definitely with the new scanner, in a future release.

**Closed by deluan** 2022-10-01 03:14 UTC
Labels: bug
