### ISSUE TITLE
[Bug]: No play menu in Artist UI

### ISSUE THREAD

**Issue by pespin** [navidrome/navidrome#2702] opened 2023-12-12 17:02 UTC
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

master

### Current Behavior

If the user goes to the Artist list UI (press "Artists" in the left menu), then for each Artist in the list, a context menu at the right appears (three dots ":" image) which allows him to "Play", "Shuffle", "Add to Playlist", etc.

However, if the user instead enters the Artist UI (by pressing the artist in the list), there's no way to do those actions from within the UI anymore.

### Expected Behavior

When entering the Artist UI screen, the user should be able to  "Play", "Shuffle", "Add to Playlist", etc.

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment] 2023-12-12 22:46
Hey, thanks for using Navidrome!

This is not a bug, it is a missing feature, and should have been opened as such, as a [Discussions/Ideas](https://github.com/navidrome/navidrome/discussions/categories/ideas).

Anyway, all features in the UI are frozen as we are working to release a new, refactored UI basedon React Admin 4. I'll close this now (as it is not a "bug"), but feel free to open an feature request/proposal in the link above.

**Closed by deluan** 2023-12-12 22:46 UTC
Labels: bug, triage
