### ISSUE TITLE
Error reading metadata from file. Skipping

### ISSUE THREAD

**Issue by Ominitay** [navidrome/navidrome#728] opened 2021-01-17 20:39 UTC
I get this error (but for all 100 of the tracks in the album)
`WARN[0002] Error reading metadata from file. Skipping    error="cannot process Music/Toby Fox/Undertale/089. SAVE the World.flac" filePath="Music/Toby Fox/Undertale/089. SAVE the World.flac"`
The tracks don't appear in the web UI because of this, and cannot be streamed.
CMUS successfully parses the metadata to the best of my understanding.
An example is in this archive: [examplefile.tar.gz](https://github.com/deluan/navidrome/files/5826798/examplefile.tar.gz)

**Comment by jwynn6** [comment] 2021-01-21 18:34
same error, different album. also FLAC.

**Comment by deluan** [comment] 2021-02-01 01:27
I can reproduce it in my dev environment. Seems like your file has some weird tag that crashes `taglib`, but I was able to import it without any issues using the `ffmpeg` extrator.

I'll take a look at this and try to figure out what tag is causing this. In the meanwhile, if this is blocking you, you have two options:

1) Remove and re-add the tags using a "modern" editor, like Picard
2) Configure Navidrome to use `ffmpeg`  as extractor (`Scanner.Extractor = "ffmpeg"`)

**Comment by Ominitay** [comment] 2021-02-01 10:24
That fixes it for me, thanks!

**Comment by jaum20** [comment] 2021-05-25 22:20
> 
> 
> I can reproduce it in my dev environment. Seems like your file has some weird tag that crashes `taglib`, but I was able to import it without any issues using the `ffmpeg` extrator.
> 
> I'll take a look and try to figure out what tag is causing this issue. In the meanwhile, if this is blocking you, you have two options:
> 
>     1. Remove and re-add the tags using a "modern" editor, like Picard
> 
>     2. Configure Navidrome to use `ffmpeg`  as extractor (`Scanner.Extractor = "ffmpeg"`)

I added ND_SCANNER_EXTRACTOR: ffmpeg to my docker-compose.yml and forced a reescan, but the problem persists

**Comment by deluan** [comment] 2021-05-26 01:24
Hey @jaum20, can you attach one of your files here? Also, can you send me (in private) the full log from a fresh install? Send it to deluan @ navidrome . org

**Comment by jaum20** [comment] 2021-05-27 02:14
> Hey @jaum20, can you attach one of your files here? Also, can you send me (in private) the full log from a fresh install? Send it to deluan @ navidrome . org

I need to do further investigations but I think the problem was due to the fact I was using a fuse-mounted volume as /music folder and maybe `taglib` runiing inside the container couldn't properly read the files.

**Comment by deluan** [comment] 2021-08-21 18:06
Hey @jaum20, are you still having this issue?

**Comment by Ominitay** [comment] 2021-08-21 18:16
Hi there! As of a few weeks ago, I've been using the docker container. I'm not sure what that changes, but all of my library has worked with it without having to change the extractor.

**Comment by deluan** [comment] 2021-08-21 18:21
There were some changes in the extractor after this issue was open, that may have fixed it for most of the cases. For those who are still having this issue, there are some files that `taglib` simply cannot read. You can try removing and re-adding all tags for these files, or use the `ffmpeg` extractor, which is more resilient to such errors.

Anyway, I'm closing this issue for now.

**Closed by deluan** 2021-08-21 18:21 UTC
Labels: bug

**Comment by jaum20** [comment] 2021-08-21 23:37
@deluan, I still having this issue after the last docker update :( 
I'm using ffmpeg

**Comment by deluan** [comment] 2021-08-21 23:42
@jaum20, can you please send me a file with error ? `deluan @ navidrome . org`

**Comment by jaum20** [comment] 2021-08-22 01:24
Basically it gives an error with any .m4a file. I sent one to you. I had to remove and recreate it to make it work again

**Comment by deluan** [comment] 2021-08-22 15:13
@jaum20 Thanks for the file. I tested it here with `taglib` and it works as expected (but no coverart):
<img width="968" alt="Screen Shot 2021-08-22 at 11 11 51 AM" src="https://user-images.githubusercontent.com/331353/130360313-758e3c51-a8df-4593-9fd1-0495eb3a7127.png">

Are you having issues with this specific file?

**Comment by jaum20** [comment] 2021-08-23 19:47
> Are you having issues with this specific file?

Yes, it was skipped by taglib

**Comment by deluan** [comment] 2021-08-23 21:31
Are you running Navidrome on Windows? Maybe you are getting this issue? https://github.com/navidrome/navidrome/issues/810

**Comment by jaum20** [comment] 2021-09-01 23:20
Not. I’m using centos

**Comment by deluan** [comment] 2021-09-03 19:19
@jaum20 Can you try with the latest develop build? After starting it, do a "Full rescan"

**Comment by karmanyaahm** [comment] 2021-10-10 04:41
I was recently having a similar issue and fixing file permissions with `chmod -R o+r /path/to/music/` (recursively allowing all users to read the files and folders) and a full scan fixed it.
