### ISSUE TITLE
Retain metadata for renamed/moved files

### ISSUE THREAD

**Issue by bagaag** [navidrome/navidrome#2149] opened 2023-02-05 16:36 UTC
### Is your feature request related to a problem? Please describe.

From time to time I may rename a folder, update file names or otherwise move things around within the music library Navidrome is pointing at. Currently, Navidrome removes the files and related metadata (starred status, rating, listening stats, playlist inclusion, etc.) and treats the renamed file(s) as new. It would be nice if metadata was retained when files were simply renamed or moved.

### Describe the solution you'd like

My thought was to use MD5 hashes for files as an identifier. If stored in the media_file table, this could be used to identify a missing/new file as the same file and update the path in the media_file table instead of treating it as a new file. I was about to write Python script to do this, but then thought it might be useful as a feature of the scanner. If agreed, I'd be willing to work on this feature.

### Describe alternative solutions that would also satisfy this problem

Another option would be to use tags instead of or in addition to a file hash. For example, if a file with path X has A, B and C tags and is found missing by the scanner, and a newly found file has those same tags, then update the path in the media_file table accordingly. 

The tag and hash methods could also be used together - with an either/or approach. 

Unfortunately, neither of these solve the problem of a file being moved on the file system while also having its tags updated at the same time.

### Additional context

This is somewhat related to Issue #1426, which is more about handling missing files. Looking at missing files within the context of found files might be a solution for that issue as well.

**Comment by dweymouth** [comment] 2023-02-05 19:20
See also https://github.com/navidrome/navidrome/issues/2068

**Comment by bagaag** [comment] 2023-03-05 17:05
Until there's a better way, I created a script to update paths in Navidrome's database so I can occasionally move things around without losing metadata. It does not monitor the file system for changes or make any changes to the file system other than updating Navidrome's database. This is a Python script that accepts two arguments: a FROM path and a TO path. These can be either a directory path with a trailing slash, or a full file path. Additional info in the header comment. 

https://gist.github.com/bagaag/3d64e3349b6ed3bfd6e01813222db055

**Comment by deluan** [comment] 2023-03-07 04:24
Thanks for reporting. Closing as a duplicate of #2068. Please subscribe that issue (with a thumbs up), to receive updates.

**Closed by deluan** 2023-03-07 04:24 UTC
Labels: enhancement
