### ISSUE TITLE
song progress bar with mozilla firefox not aligned properly

### ISSUE THREAD

**Issue by gg-dev-05** [navidrome/navidrome#865] opened 2021-03-21 12:02 UTC
The seek (song progress bar) is touching the bottom of page while using firefox but works fine with google chrome

![screenshot](https://user-images.githubusercontent.com/59741135/111904083-0120e980-8a6b-11eb-9634-fad9e8afd6e3.png)

**Comment by gg-dev-05** [comment] 2021-03-21 13:45
@deluan Can I work on this issue as it seems quite easy to fix with a few lines of css.

**Comment by jvoisin** [comment] 2021-03-21 14:00
Sure :)

**Comment by deluan** [comment] 2021-03-21 16:34
This is most probably an issue with the [react-jinke-music-player](https://github.com/lijinke666/react-music-player). Check if their [demo](https://www.lijinke.cn/react-music-player/) also has this issue.

**Comment by gg-dev-05** [comment] 2021-03-21 17:07
The [demo](https://www.lijinke.cn/react-music-player/) looks fine.

![Screenshot_2021-03-21 react-jinke-music-player](https://user-images.githubusercontent.com/59741135/111913869-ca13fd80-8a95-11eb-8a89-3f2e6d6e465b.png)

**Comment by sakshi-choudhary** [comment] 2021-03-21 17:58
If no one is working on this, Can I take up this issue?

**Comment by deluan** [comment] 2021-03-21 19:26
I can't seem to reproduce it in my environment with Firefox:
<img width="1114" alt="Screen Shot 2021-03-21 at 3 24 40 PM" src="https://user-images.githubusercontent.com/331353/111918043-9b783180-8a59-11eb-964e-3020cbda85a0.png">

And based on the size of the album cover, seems that there is some sort of font resizing going on in your browser... Can you double check this please?

**Comment by gg-dev-05** [comment] 2021-03-21 23:34
> And based on the size of the album cover, seems that there is some sort of font resizing going on in your browser... Can you double check this please?

The default font size in my firefox was 24px thus it was causing all these issues I changed it back to 16px and now it looks good.

But I was wondering why these other players like spotify and [react-jinke-music-player](https://www.lijinke.cn/react-music-player/) have no effect of changing font sizes. Shouldn't navidrome also be same i.e it looks same on all font sizes or at least we should prevent the content from overflowing on different font sizes.

![image](https://user-images.githubusercontent.com/59741135/111924554-3e1cc880-8acb-11eb-881a-269518f28647.png)

**Comment by deluan** [comment] 2021-03-21 23:48
> Shouldn't navidrome also be same i.e it looks same on all font sizes or at least we should prevent the content from overflowing on different font sizes.

Agree, not sure how to accomplish this in a simple way. Feel free to suggest a solution. This may be related to #232

**Comment by Dnouv** [comment] 2021-03-22 05:56
@deluan, maybe the problem is in the CSS units used; in most of the styles, the units are px, which are considered as absolute units and do not vary with the changing font size; the possible solution might be using the em units, they vary with the font size.

**Comment by deluan** [comment] 2021-03-22 14:33
Feel free to experiment with it :)

**Comment by Dnouv** [comment] 2021-03-22 17:33
@deluan, the same issue is there for react-jinke-music-player, so should I fix it for the navidrome site or raise an issue in the react-jinke-player repository? Please let me know.

**Comment by deluan** [comment] 2021-03-22 17:43
If I understand correctly, you'll wont be able to fix it completely without also changing `react-jinke-player`, is that right? If that's the case, you can try sending a PR to the `react-jinke-player` project, I'm sure the dev will be happy to accept/discuss it with you.

**Comment by Dnouv** [comment] 2021-03-22 19:40
Yeah, we will need to make changes in the `react-jinke-music-player/assets/index.css`, or else we could fix the site's font size independent of the default font size of the browser.
Thank you for your prompt reply.

**Comment by armedev** [comment] 2021-03-23 12:29
@Dnouv the quick fix for this issue is giving a fixed font-size (16 px) for the HTML tag in the index.css which will update the browsers font-size then we can use 'em' anywhere :)

**Comment by Dnouv** [comment] 2021-03-23 13:24
Yeah, @armedev, thanks for the suggestion, the same I have mentioned in the comment.

> `react-jinke-music-player/assets/index.css`, or else we could fix the site's font size independent of the default font size of the browser.
>

**Comment by armedev** [comment] 2021-04-09 17:51
@deluan can I solve this by changing the font size to default (16px).

**Comment by deluan** [comment] 2021-04-09 18:21
I prefer to understand why [react-music-player](https://github.com/lijinke666/react-music-player) does not have this issue, than blindly applying this "fix". Do we know all the repercussions of changing this? As a rule of thumb, I prefer to not apply global CSS styles....

**Comment by armedev** [comment] 2021-04-09 18:30
yeah, I also thought of it where the end-user really wants his font size to be more than the default and surprisingly finds Navidrome with the default font size of 16px which is bad.
anyway I was wondering how to fix it because when I tried their [demo](https://lijinke666.github.io/react-music-player/) player if I change the font size it is not affecting the player on their site.

**Comment by deluan** [comment] 2021-04-09 18:33
Maybe this is caused by a change in style in our code? It could be caused by us overriding the `renderAudioTitle` property

**Comment by armedev** [comment] 2021-04-09 19:13
@deluan I figured it out, the br tag is the root cause for the issue.

**Comment by deluan** [comment] 2021-04-09 19:22
Yes, but please do extensive testing (various resolutions, various breakpoints: xs, sm, md, etc..., various font sizes) before doing so. We don't want a solution that fix one use case and break another ;)

**Comment by armedev** [comment] 2021-04-10 08:46
@deluan what do you suggest for keeping the font size in the player to a constant value, because increasing the font-size wrt to the browser font size will break the whole layout of the player.

**Comment by deluan** [comment] 2021-04-11 04:16
I don't have any recommendation here, don't really know how to handle this. Maybe the best solution here is to leave it as it is...?

**Comment by armedev** [comment] 2021-04-11 04:46
Actually it has a global fix try applying below styles to class `progress-bar-content` in index.css
`display: flex;
flex-direction: column;`

after applying the above styles we can dynamically change font size and have the layout working fine

**Closed** 2021-04-23 22:06 UTC
Labels: good first issue, web ui
