### ISSUE TITLE
Navidrome becomes unresponsive some times.

### ISSUE THREAD

**Issue by blmhemu** [navidrome/navidrome#1515] opened 2021-12-13 17:01 UTC
### Description
Navidrome becomes unresponsive and returns some errors sometimes.

### Expected Behaviour
Responsive behaviour

### Steps to reproduce
Nothing... Normal docker setup

### Platform information

 - Navidrome version: v0.47.0 
 - Browser and version: Firefox (latest), some android clients
 - Operating System: docker (official)

### Additional information

```
level=error msg="SQL: `SELECT * FROM user WHERE user_name LIKE ?`" args="['username_redacted']" elapsedTime=15.02s error="database is locked" requestId=jcukyasgdvucadifvbsdf rowsAffected=1
level=error msg="Authenticated username not found in DB" requestId=safdfsvsgdfxz/vasdfdvsfdgsd username=username_redacted
```

**Comment by blmhemu** [comment] 2021-12-19 05:33
Could this be related to https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked

**Comment by deluan** [comment] 2022-01-06 00:45
@blmhemu Maybe, but this was fixed a looong time ago, and should not be happening with newer versions. Is your `data` folder hosted in a network drive? SQLite3 does not support opening the DB from a network share.

**Comment by blmhemu** [comment] 2022-01-07 03:38
Ok, I think that may be the issue then! I am curious as to how else do you guys host the data files ? (other than locally)

**Comment by deluan** [comment] 2022-01-07 18:45
With SQLite3, you don't have an option: You _have to_ host it locally. And it is the same with [all software](https://en.wikipedia.org/wiki/SQLite#Notable_uses) that uses SQLite3 (Plex, Sonarr, Firefox, etc...). What I personally do is to backup the DB daily.

I'm gonna close this issue now that you figure out the root cause, but feel free to add any concerns regarding this subject.

**Closed by deluan** 2022-01-07 18:45 UTC
Labels: bug
