### ISSUE TITLE
Track position get displayed wrongly

### ISSUE THREAD

**Issue by DJoLoAo** [navidrome/navidrome#1982] opened 2022-11-10 10:04 UTC
### Description

I use Navidrome for my digitalized vinyl collection. All files are in flac.
The correct track positions in this case is A1,A2 etc

### Expected Behaviour

List the songs of an album in the correct order. Display A1,A2 instead of 0.

### Additional information

As I can see is TRCK is set to integer. Is it possible to change this?

**Comment by deluan** [comment] 2022-11-10 15:19
Thanks for reporting. This is not a "bug", the track numbering was based on the MP3 tags, where track number is numeric. Anyway, this is a duplicate of #1652, please follow any updates on that issue.

**Closed by deluan** 2022-11-10 15:19 UTC
Labels: bug
