### ISSUE TITLE
transcode no working

### ISSUE THREAD

**Issue by ioi-c** [navidrome/navidrome#1539] opened 2021-12-26 05:06 UTC
I  have tried many times but transcode function still not working .

### Description

I install it by docker ,the parameter like bellow,  contain the  config the transcode ,but it don't work.

docker-compose.yml
---
version: "3"
services:
        navidrome:
                image: deluan/navidrome:latest
                container_name: navidrome
                user: 0:0 
                ports:
                        - "4533:4533"
                restart: unless-stopped
                environment:
                        ND_SCANSCHEDULE: 2400h
                        ND_SESSIONTIMEOUT: 240h
                        ND_LOGLEVEL: info  
                        ND_BASEURL: ""
                        **ND_ENABLETRANSCODINGCONFIG: "true"
                        ND_TRANSCODINGCACHESIZE: "4000M"
                        ND_IMAGECACHESIZE: "4000M"**
                volumes:
                        - "/3t/nas/docker_data/navidrome/data:/data"
                        - "/3t/nas/media/music:/music:ro"

**webUI:**
 mp3 audio | mp3 | 256 | ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -f mp3 -
opus audio | opus | 256 | ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -c:a libopus -f opus -

Docker log:
 _   _             _     _

| \ | |           (_)   | |

|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___

| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \

| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/

\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|

                          Version: 0.47.0 (8c7d95c1)

time="2021-12-26T04:47:48Z" level=info msg="goose: no migrations to run. current version: 20211105162746\n"

time="2021-12-26T04:47:48Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music

time="2021-12-26T04:47:48Z" level=info msg="Creating Image cache" maxSize="4.0 GB" path=/data/cache/images

time="2021-12-26T04:47:48Z" level=info msg="Starting scheduler"

time="2021-12-26T04:47:48Z" level=info msg="Scheduling periodic scan" schedule="@every 2400h"

time="2021-12-26T04:47:48Z" level=info msg="Setting Session Timeout" value=240h

time="2021-12-26T04:47:48Z" level=info msg="Login rate limit set" requestLimit=5 windowLength=20s

time="2021-12-26T04:47:48Z" level=info msg="Found ffmpeg" path=/usr/bin/ffmpeg

time="2021-12-26T04:47:48Z" level=info msg="Spotify integration is not enabled: missing ID/Secret"

time="2021-12-26T04:47:48Z" level=info msg="Mounting Native API routes" path=/api

time="2021-12-26T04:47:48Z" level=error msg="Agent not available. Check configuration" name=spotify

time="2021-12-26T04:47:48Z" level=info msg="Creating Transcoding cache" maxSize="4.0 GB" path=/data/cache/transcoding

time="2021-12-26T04:47:48Z" level=info msg="Finished initializing cache" cache=Transcoding elapsedTime=3.1ms maxSize=4000M

time="2021-12-26T04:47:48Z" level=info msg="Mounting Subsonic API routes" path=/rest

time="2021-12-26T04:47:48Z" level=info msg="Mounting LastFM Auth routes" path=/api/lastfm

time="2021-12-26T04:47:48Z" level=info msg="Mounting ListenBrainz Auth routes" path=/api/listenbrainz

time="2021-12-26T04:47:48Z" level=info msg="Mounting WebUI routes" path=/app

time="2021-12-26T04:47:48Z" level=info msg="Navidrome server is ready!" address="0.0.0.0:4533" startupTime=47.5ms

time="2021-12-26T04:47:49Z" level=info msg="Finished initializing cache" cache=Image elapsedTime=178.4ms maxSize=4000M

time="2021-12-26T04:48:09Z" level=info msg="Streaming file" artist="Avril Lavigne" bitRate=0 cached=false format=raw originalBitRate=1001 originalFormat=flac title="Anything but Ordinary" **transcoding=false** user=admin

time="2021-12-26T04:48:10Z" level=info msg="Now Playing" artist="Avril Lavigne" player="NavidromeUI [Firefox/Windows]" title="Anything but Ordinary" user=admin

**time="2021-12-26T04:48:18Z" level=info msg="Streaming file" artist="Avril Lavigne" bitRate=0 cached=false format=raw originalBitRate=972 originalFormat=flac title="I'm with You" **transcoding=false** user=admin

time="2021-12-26T04:48:18Z" level=info msg="Now Playing" artist="Avril Lavigne" player="NavidromeUI [Firefox/Windows]" title="I'm with You" user=admin**

### Expected Behaviour

how to make the transcode working?

 - Navidrome version:    Version: 0.47.0 (8c7d95c1)
 
 - Operating System: Armbian docker 
 -
###Additional information
 Browser and version:        Firefox v95.0.1 @WIN7 
 APP:  DSub 5.52@andriod

**Comment by Dnouv** [comment] 2021-12-26 20:30
@ioi-c, thanks for reporting the issue. Could you once set the `loglevel` to debug and check whether the Navidrome is catching the right variable,
```
1:32:38 AM GO.1 |   _   _             _     _
1:32:38 AM GO.1 |  | \ | |           (_)   | |
1:32:38 AM GO.1 |  |  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___1:32:38 AM GO.1 |  | . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
1:32:38 AM GO.1 |  | |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
1:32:38 AM GO.1 |  \_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
1:32:38 AM GO.1 |                                          Version: dev
1:32:38 AM GO.1 |  Loaded configuration from 'dnouv/ospr/navidrome': &conf.configOptions{
1:32:38 AM GO.1 |      Port:                       4633,
1:32:38 AM GO.1 |      MusicFolder:                "../nm",
1:32:38 AM GO.1 |      DataFolder:                 "./data",
1:32:38 AM GO.1 |      DbPath:                     "data/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on",
1:32:38 AM GO.1 |      LogLevel:                   "debug",
1:32:38 AM GO.1 |      BaseURL:                    "",

*******************************THIS
1:32:38 AM GO.1 |      EnableTranscodingConfig:    false,  <----- This one to be checked
______________________________________________________
1:32:38 AM GO.1 |      EnableDownloads:            true,
``` 
I hope this may be of some help. If it is `false`, then try restarting Navidrome, or you could try changing ("true" -> true). If the issue is not resolved after following the above steps, please feel free to comment.
Thank you!

P.S. Credits for the above troubleshoot steps to deluan.

**Comment by ioi-c** [comment] 2021-12-27 12:14
firstly change the "true"  to true ,the docker couldn't run :

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
root@N1:/3t/nas/docker_data/navidrome# cat  docker-compose.yml 
---
version: "3"
services:
        navidrome:
                image: deluan/navidrome:latest
                container_name: navidrome
                user: 0:0 
                ports:
                        - "4533:4533"
                restart: unless-stopped
                environment:
                        ND_SCANSCHEDULE: 2400h
                        ND_SESSIONTIMEOUT: 240h
                        ND_LOGLEVEL: debug  
                        ND_BASEURL: ""
                        ND_ENABLETRANSCODINGCONFIG: true
                        ND_TRANSCODINGCACHESIZE: "4000M"
                        ND_IMAGECACHESIZE: "4000M"
                volumes:
                        - "/3t/nas/docker_data/navidrome/data:/data"
                        - "/3t/nas/media/music:/music:ro"
root@N1:/3t/nas/docker_data/navidrome# vi docker-compose.yml 
root@N1:/3t/nas/docker_data/navidrome#  docker run --rm   -v /var/run/docker.sock:/var/run/docker.sock   -v "$PWD:$PWD"   -w="$PWD"   linuxserver/docker-compose   up -d
The Compose file './docker-compose.yml' is invalid because:
services.navidrome.environment.ND_ENABLETRANSCODINGCONFIG contains true, which is an invalid type, it should be a string, number, or a null
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


change back to "true", it catched the " EnableTranscodingConfig:    true,,"   but the transcode still no working 



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ScanSchedule:               "@every 2400h",,
    SessionTimeout:             864000000000000,,
    BaseURL:                    "",,
    UILoginBackgroundURL:       "https://source.unsplash.com/collection/20072696/1600x900",,
    EnableTranscodingConfig:    true,,
    EnableDownloads:            true,,
    EnableExternalServices:     true,,
    TranscodingCacheSize:       "4000M",,
    ImageCacheSize:             "4000M",,
    AutoImportPlaylists:        true,,
    PlaylistsPath:              ".:**/**",,
    SearchFullString:           false,,
    RecentlyAddedByModTime:     false,,
    IgnoredArticles:            "The El La Los Las Le Les Os As O A",,
    IndexGroups:                "A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ) [Unknown]([)",,
    ProbeCommand:               "ffmpeg %s -f ffmetadata",,
    CoverArtPriority:           "embedded, cover.*, folder.*, front.*",,
    CoverJpegQuality:           75,,
    UIWelcomeMessage:           "",,
    EnableGravatar:             false,,
    EnableFavourites:           true,,
    EnableStarRating:           true,,
    EnableUserEditing:          true,,
    DefaultTheme:               "Dark",,
    EnableCoverAnimation:       true,,
    GATrackingID:               "",,
    EnableLogRedacting:         true,,
    AuthRequestLimit:           5,,
    AuthWindowLength:           20000000000,,
    PasswordEncryptionKey:      "[REDACTED]",,
    ReverseProxyUserHeader:     "Remote-User",,
    ReverseProxyWhitelist:      "",,
    Scanner:                    conf.scannerOptions{Extractor:"taglib", GenreSeparators:";/,"},,
    Agents:                     "lastfm,spotify",,
    LastFM:                     conf.lastfmOptions{Enabled:true, ApiKey:"[REDACTED]", Secret:"[REDACTED]", Language:"en"},,
    Spotify:                    conf.spotifyOptions{},,
    ListenBrainz:               conf.listenBrainzOptions{Enabled:true},,
    DevLogSourceLine:           false,,
    DevLogLevels:               {},,
    DevAutoCreateAdminPassword: "",,
    DevAutoLoginUsername:       "",,
    DevPreCacheAlbumArtwork:    false,,
    DevFastAccessCoverArt:      false,,
    DevActivityPanel:           true,,
    DevEnableShare:             false,,
    DevSidebarPlaylists:        true,,
    DevEnableBufferedScrobble:  true,,
    DevShowArtistPage:          true,,
},
time="2021-12-27T12:00:33Z" level=info msg="goose: no migrations to run. current version: 20211105162746\n",
time="2021-12-27T12:00:33Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music,
time="2021-12-27T12:00:33Z" level=info msg="Creating Image cache" maxSize="4.0 GB" path=/data/cache/images,
time="2021-12-27T12:00:33Z" level=info msg="Starting scheduler",
time="2021-12-27T12:00:33Z" level=debug msg="Scheduler: start",
time="2021-12-27T12:00:33Z" level=info msg="Scheduling periodic scan" schedule="@every 2400h",
time="2021-12-27T12:00:33Z" level=debug msg="Scheduler: added" entry=1 next="2022-04-06 12:00:33 +0000 UTC" now="2021-12-27 12:00:33.117587353 +0000 UTC",
time="2021-12-27T12:00:33Z" level=info msg="Setting Session Timeout" value=240h,
time="2021-12-27T12:00:33Z" level=info msg="Login rate limit set" requestLimit=5 windowLength=20s,
time="2021-12-27T12:00:33Z" level=info msg="Found ffmpeg" path=/usr/bin/ffmpeg,
time="2021-12-27T12:00:33Z" level=debug msg="Last.FM integration is ENABLED",
time="2021-12-27T12:00:33Z" level=info msg="Spotify integration is not enabled: missing ID/Secret",
time="2021-12-27T12:00:33Z" level=info msg="Mounting Native API routes" path=/api,
time="2021-12-27T12:00:33Z" level=error msg="Agent not available. Check configuration" name=spotify,
time="2021-12-27T12:00:33Z" level=info msg="Creating Transcoding cache" maxSize="4.0 GB" path=/data/cache/transcoding,
time="2021-12-27T12:00:33Z" level=debug msg="Loaded cache" dir=/data/cache/transcoding numItems=7,
time="2021-12-27T12:00:33Z" level=info msg="Finished initializing cache" cache=Transcoding elapsedTime=2.9ms maxSize=4000M,
time="2021-12-27T12:00:33Z" level=info msg="Mounting Subsonic API routes" path=/rest,
time="2021-12-27T12:00:33Z" level=info msg="Mounting LastFM Auth routes" path=/api/lastfm,
time="2021-12-27T12:00:33Z" level=info msg="Mounting ListenBrainz Auth routes" path=/api/listenbrainz,
time="2021-12-27T12:00:33Z" level=info msg="Mounting WebUI routes" path=/app,
time="2021-12-27T12:00:33Z" level=info msg="Navidrome server is ready!" address="0.0.0.0:4533" startupTime=54.4ms,
time="2021-12-27T12:00:33Z" level=debug msg="Loaded cache" dir=/data/cache/images numItems=722,
time="2021-12-27T12:00:33Z" level=info msg="Finished initializing cache" cache=Image elapsedTime=197.3ms maxSize=4000M,
time="2021-12-27T12:00:35Z" level=debug msg="Executing initial scan",
time="2021-12-27T12:00:35Z" level=debug msg="Scanning folder" folder=/music lastModifiedSince="2021-12-27 11:58:09.638 +0000 UTC",
time="2021-12-27T12:00:35Z" level=debug msg="Directory tree loaded from DB" elapsed=34.4ms total=81,
time="2021-12-27T12:00:35Z" level=debug msg="Finished deleted folders check" elapsed="61.626µs" total=0,
time="2021-12-27T12:00:35Z" level=debug msg="Finished reading directories from filesystem" elapsed=79.1ms,
time="2021-12-27T12:00:35Z" level=debug msg="No changes found in Music Folder" elapsed=115.2ms folder=/music,
time="2021-12-27T12:00:35Z" level=debug msg="Finished initial scan",
time="2021-12-27T12:01:01Z" level=debug msg="API: New request /rest/stream.view" client=DSub requestId=1fd11e682f06/RX85oRAo4E-000001 username=admin version=1.2.0,
time="2021-12-27T12:01:01Z" level=debug msg="API: New request /rest/savePlayQueue.view" client=DSub requestId=1fd11e682f06/RX85oRAo4E-000002 username=admin version=1.2.0,
time="2021-12-27T12:01:02Z" level=debug msg="API: Successful response" requestId=1fd11e682f06/RX85oRAo4E-000002 status=OK,
time="2021-12-27T12:01:02Z" level=debug msg="Streaming RAW file" id=fe15e7a4119b1e8c089405b709ab2e7d originalBitrate=1085 originalFormat=flac path="/music/专辑/Goodbye Lullaby (Deluxe Edition)/Avril Lavigne-4 Real.flac" requestBitrate=64 requestFormat= requestId=1fd11e682f06/RX85oRAo4E-000001 selectedBitrate=0 selectedFormat=raw,
time="2021-12-27T12:01:02Z" level=info msg="Streaming file" artist="Avril Lavigne" bitRate=0 cached=false format=raw originalBitRate=1085 originalFormat=flac title="4 Real" transcoding=false user=admin,
time="2021-12-27T12:01:02Z" level=debug msg="HTTP: GET http://192.168.2.254:4533/rest/savePlayQueue.view?u=admin&s=[REDACTED]&t=[REDACTED]&v=1.2.0&c=DSub&id=fe15e7a4119b1e8c089405b709ab2e7d&id=0416dd9ceae8b49b14b57c21e29a83f7&id=591c657c08686da0516ae503b184262f&id=996a0522b75dd8242014764ddcd2b8fb&id=ac39e1d0944c7c386c3602866c408a6d&id=46e8f47f08538f240095a222e08cf4cb&id=daf7da8aa21a9f03627602feeb2aba10&id=975a60e97109f4852eaa35d04b1561fe&id=c2faed697b4c1f3f8a759abca54702b3&id=70e9e808863612bcb8983e9df6801f6a&id=0b305500038fccf9266331ceb3194dde&id=23a9ef41fa7ce993d504be0696e7cd41&id=a2ea828a2db47c04fac67e065e41b728&id=0c01507145b159fa9c24a09473afcfd0&id=1c4607dc24c0fa481834afcf1ea1aa44&current=fe15e7a4119b1e8c089405b709ab2e7d&position=0" elapsedTime=31.9ms httpStatus=200 remoteAddr="192.168.2.253:42502" requestId=1fd11e682f06/RX85oRAo4E-000002 responseSize=155 userAgent=DSub,
time="2021-12-27T12:01:02Z" level=debug msg="API: New request /rest/scrobble.view" client=DSub requestId=1fd11e682f06/RX85oRAo4E-000003 username=admin version=1.2.0,
time="2021-12-27T12:01:02Z" level=info msg="Now Playing" artist="Avril Lavigne" player="DSub [DSub]" title="4 Real" user=admin,
time="2021-12-27T12:01:02Z" level=debug msg="API: Successful response" requestId=1fd11e682f06/RX85oRAo4E-000003 status=OK,
time="2021-12-27T12:01:02Z" level=debug msg="HTTP: GET http://192.168.2.254:4533/rest/scrobble.view?u=admin&s=[REDACTED]&t=[REDACTED]&v=1.2.0&c=DSub&id=fe15e7a4119b1e8c089405b709ab2e7d&submission=false" elapsedTime=14.1ms httpStatus=200 remoteAddr="192.168.2.253:42502" requestId=1fd11e682f06/RX85oRAo4E-000003 responseSize=155 userAgent=DSub,
time="2021-12-27T12:01:03Z" level=debug msg="API: New request /rest/savePlayQueue.view" client=DSub requestId=1fd11e682f06/RX85oRAo4E-000004 username=admin version=1.2.0,
time="2021-12-27T12:01:03Z" level=debug msg="API: Successful response" requestId=1fd11e682f06/RX85oRAo4E-000004 status=OK,
time="2021-12-27T12:01:03Z" level=debug msg="HTTP: GET http://192.168.2.254:4533/rest/savePlayQueue.view?u=admin&s=[REDACTED]&t=[REDACTED]&v=1.2.0&c=DSub&id=fe15e7a4119b1e8c089405b709ab2e7d&id=0416dd9ceae8b49b14b57c21e29a83f7&id=591c657c08686da0516ae503b184262f&id=996a0522b75dd8242014764ddcd2b8fb&id=ac39e1d0944c7c386c3602866c408a6d&id=46e8f47f08538f240095a222e08cf4cb&id=daf7da8aa21a9f03627602feeb2aba10&id=975a60e97109f4852eaa35d04b1561fe&id=c2faed697b4c1f3f8a759abca54702b3&id=70e9e808863612bcb8983e9df6801f6a&id=0b305500038fccf9266331ceb3194dde&id=23a9ef41fa7ce993d504be0696e7cd41&id=a2ea828a2db47c04fac67e065e41b728&id=0c01507145b159fa9c24a09473afcfd0&id=1c4607dc24c0fa481834afcf1ea1aa44&current=fe15e7a4119b1e8c089405b709ab2e7d&position=0" elapsedTime=8.2ms httpStatus=200 remoteAddr="192.168.2.253:42506" requestId=1fd11e682f06/RX85oRAo4E-000004 responseSize=155 userAgent=DSub,
time="2021-12-27T12:01:20Z" level=debug msg="HTTP: GET http://192.168.2.254:4533/rest/stream.view?u=admin&s=[REDACTED]&t=[REDACTED]&v=1.2.0&c=DSub&id=fe15e7a4119b1e8c089405b709ab2e7d&maxBitRate=64" elapsedTime=18.33s httpStatus=200 remoteAddr="192.168.2.253:42500" requestId=1fd11e682f06/RX85oRAo4E-000001 responseSize=28256315 userAgent=DSub,
time="2021-12-27T12:01:20Z" level=debug msg="API: New request /rest/stream.view" client=DSub requestId=1fd11e682f06/RX85oRAo4E-000006 username=admin version=1.2.0,
time="2021-12-27T12:01:20Z" level=debug msg="Streaming RAW file" id=0416dd9ceae8b49b14b57c21e29a83f7 originalBitrate=904 originalFormat=flac path="/music/专辑/Goodbye Lullaby (Deluxe Edition)/Avril Lavigne-Alice.flac" requestBitrate=64 requestFormat= requestId=1fd11e682f06/RX85oRAo4E-000006 selectedBitrate=0 selectedFormat=raw,
time="2021-12-27T12:01:20Z" level=info msg="Streaming file" artist="Avril Lavigne" bitRate=0 cached=false format=raw originalBitRate=904 originalFormat=flac title=Alice transcoding=false user=admin,
time="2021-12-27T12:01:22Z" level=debug msg="API: New request /rest/savePlayQueue.view" client=DSub requestId=1fd11e682f06/RX85oRAo4E-000007 username=admin version=1.2.0,
time="2021-12-27T12:01:22Z" level=debug msg="API: Successful response" requestId=1fd11e682f06/RX85oRAo4E-000007 status=OK,
time="2021-12-27T12:01:22Z" level=debug msg="HTTP: GET http://192.168.2.254:4533/rest/savePlayQueue.view?u=admin&s=[REDACTED]&t=[REDACTED]&v=1.2.0&c=DSub&id=fe15e7a4119b1e8c089405b709ab2e7d&id=0416dd9ceae8b49b14b57c21e29a83f7&id=591c657c08686da0516ae503b184262f&id=996a0522b75dd8242014764ddcd2b8fb&id=ac39e1d0944c7c386c3602866c408a6d&id=46e8f47f08538f240095a222e08cf4cb&id=daf7da8aa21a9f03627602feeb2aba10&id=975a60e97109f4852eaa35d04b1561fe&id=c2faed697b4c1f3f8a759abca54702b3&id=70e9e808863612bcb8983e9df6801f6a&id=0b305500038fccf9266331ceb3194dde&id=23a9ef41fa7ce993d504be0696e7cd41&id=a2ea828a2db47c04fac67e065e41b728&id=0c01507145b159fa9c24a09473afcfd0&id=1c4607dc24c0fa481834afcf1ea1aa44&current=fe15e7a4119b1e8c089405b709ab2e7d&position=18515" elapsedTime=7.7ms httpStatus=200 remoteAddr="192.168.2.253:42502" requestId=1fd11e682f06/RX85oRAo4E-000007 responseSize=155 userAgent=DSub,

**Comment by deluan** [comment] 2022-12-07 00:44
Hey @ioi-c , are you still having issues with this?

**Comment by deluan** [comment] 2022-12-19 02:27
Closing as it seems to be a config issue. Feel free to reopen if you think otherwise.

**Closed by deluan** 2022-12-19 02:27 UTC
Labels: bug
