### ISSUE TITLE
Improper display of song play time

### ISSUE THREAD

**Issue by Dnouv** [navidrome/navidrome#876] opened 2021-03-22 12:49 UTC
The song play time in the player is not completely visible on some screen sizes, it can be seen in the attached screenshot that the duration 00:00-----01:02 is not completely visible the only visible play time is as "00-----01"
The issue screen:
<img width="437" alt="navid_bug" src="https://user-images.githubusercontent.com/61188295/111991685-95a64d00-8b3a-11eb-92fb-f8463eb682fc.png">

Expected duration screen:
<img width="508" alt="navid_bugnv" src="https://user-images.githubusercontent.com/61188295/111991756-a656c300-8b3a-11eb-81d6-e0d903c4d737.png">

@deluan I would like to work on this issue, could you have a look.
Thank you!

**Comment by jvoisin** [comment] 2021-03-22 19:39
I think that this should be tackled upstream in [react-music-player]( https://github.com/xiaolin3303/react-music-player ).

**Comment by Dnouv** [comment] 2021-03-22 19:49
Sorry @jvoisin, but I am not sure if I fully understand your reply. How is this issue related to `react-music-player`? Ain't we using `react-jinke-music-player`.

**Comment by jvoisin** [comment] 2021-03-22 19:54
I meant `react-jinke-music-player`, my bad

**Comment by Dnouv** [comment] 2021-03-22 20:00
Thank you for your prompt reply, @jvoisin . I checked on the `react-jinke-music-player` site, but the issue was not present; it's only on navidrome.

**Comment by jvoisin** [comment] 2021-03-22 20:04
I meant that the problem is likely coming from `react-jinke-music-player`, and should be fixed there, instead of being hacked away in navidrome.

**Comment by deluan** [comment] 2021-03-22 20:09
This is related to #520, we need to set a proper mobile media query. In their demo they set it to 1024px: https://github.com/lijinke666/react-music-player/blob/master/example/example.js#L256, but I think this is too high

**Comment by Dnouv** [comment] 2021-03-22 20:12
I experimented with it, and it is most likely the issue is with the `theme-breakpoints`. I could give it a try, may I?

**Comment by deluan** [comment] 2021-03-22 20:25
Sure. You can always try to fix bugs without asking :)

**Comment by JayKaku** [comment] 2021-04-13 06:39
Is the issue still open ? like @Dnouv has created a pr

**Comment by Dnouv** [comment] 2021-04-13 15:02
Sorry @JayKaku, but the PR is still in progress, and the issue might close soon enough. Thanks for reviewing the issue.

**Comment by JayKaku** [comment] 2021-04-14 08:19
Okay thank you for the update.

**Closed** 2021-04-23 23:04 UTC
